(function(){
  'use strict';
  const F=window.PANTA_V17_FIXTURE;
  const V=F.v16;
  const R=window.PantaRuntime;
  const app=document.getElementById('app');
  const drawer=document.getElementById('drawer');
  const modal=document.getElementById('modal');
  const toast=document.getElementById('toast');

  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const qBy=id=>V.question_spine.find(q=>q.id===id);
  const personBy=id=>V.people.find(p=>p.id===id)||V.deal.team.find(p=>p.id===id);
  const artifactBy=id=>V.artifacts.find(a=>a.id===id);
  const getQView=(question,state)=>question.versions[state.settled?'post-cdd':'post-qoe']||question.versions['firm-initial'];
  const initials=name=>String(name||'').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  const dispositionClass=v=>String(v||'').toLowerCase().replace(/_/g,'-');

  function avatar(personOrName,size=''){
    const p=typeof personOrName==='string'?(V.people.find(x=>x.name===personOrName)||V.deal.team.find(x=>x.name===personOrName)):personOrName;
    const name=p?.name||String(personOrName||'Unknown');
    return `<span class="avatar ${size}">${esc(p?.initials||initials(name))}</span>`;
  }
  function pill(label,cls=''){return `<span class="status-pill ${esc(cls||dispositionClass(label))}">${esc(label)}</span>`}
  function icon(name){const map={command:'⌁',work:'↗',foundations:'⌂',unknowns:'?',shadow:'◐',artifacts:'▤',registry:'≡',replay:'↶',scenario:'⑂',decision:'◆',execution:'⇥',fund:'◎',deal:'◉'};return map[name]||'·'}

  function contextRail(state){
    const dealViews=[
      ['deal-command','command','Command'],['work','work','Work'],['foundations','foundations','Foundations'],['unknowns','unknowns','Unknowns'],['shadow-ic','shadow','Shadow IC'],['artifacts','artifacts','Artifacts'],['registry','registry','Registry'],['replay','replay','Replay']
    ];
    const special=[['scenario','scenario','Scenario Lab'],['decision','decision','Decision Room'],['execution','execution','Execution Room']];
    return `<aside class="context-rail">
      <button class="panta-mark" data-action="open-fund"><span>P</span><strong>PANTA</strong></button>
      <div class="scale-switch">
        <button data-scale="fund" class="${state.scale==='fund'?'active':''}">${icon('fund')}<span>Fund</span></button>
        <button data-scale="deal" class="${state.scale==='deal'?'active':''}">${icon('deal')}<span>Deal</span></button>
      </div>
      ${state.scale==='deal'?`<nav class="rail-nav">
        <small>DEAL WORLD</small>
        ${dealViews.map(([view,ic,label])=>`<button data-nav="${view}" class="${state.view===view?'active':''}"><i>${icon(ic)}</i><span>${label}</span>${view==='unknowns'?'<b>5</b>':''}</button>`).join('')}
        <small>SPECIAL ROOMS</small>
        ${special.map(([view,ic,label])=>`<button data-nav="${view}" class="${state.view===view?'active':''}"><i>${icon(ic)}</i><span>${label}</span></button>`).join('')}
      </nav>`:`<div class="rail-fund-note"><small>FUND COMMAND</small><strong>One state.<br>Role-projected.</strong></div>`}
      <div class="rail-footer"><button data-action="open-command" title="Command bar">⌘K</button><button data-action="toggle-motion">${state.reducedMotion?'M−':'M+'}</button></div>
    </aside>`;
  }

  function objectiveHeader(state){
    const isFund=state.scale==='fund';
    return `<header class="objective-header">
      <div class="objective-context">
        <span class="eyebrow">${isFund?'FUND COMMAND':'CURRENT OBJECTIVE'}</span>
        <h1>${isFund?'Allocate attention to the decisions that matter now':esc(F.deal.objective.statement)}</h1>
        <div class="objective-meta">${isFund?`<span>${F.fund.date}</span><span>4 live situations</span><span>${state.role==='partner'?'Partner authority projection':'Associate execution projection'}</span>`:`<span>Confirmatory diligence</span><span>Deadline ${esc(F.deal.objective.deadline)}</span><span>Current ${esc(F.deal.branches.current)}</span>`}</div>
      </div>
      <div class="objective-controls">
        <div class="connection-chip ${state.mode}"><i></i>${state.mode==='connected'?'BACKEND CONNECTED':'INTEGRATION DEMO'}</div>
        <div class="segmented"><button data-role="associate" class="${state.role==='associate'?'active':''}">Associate</button><button data-role="partner" class="${state.role==='partner'?'active':''}">Partner</button></div>
        ${!isFund?`<div class="lens-select"><span>Lens</span><select data-lens>${['command','evidence','economics','work','relationships','time'].map(x=>`<option value="${x}" ${state.lens===x?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></div>`:''}
      </div>
    </header>`;
  }

  function causalTimeRail(state){
    if(state.scale!=='deal')return '';
    const selected=state.settled?'post-cdd':state.selectedReplayId;
    return `<footer class="causal-time-rail"><span class="rail-label">CAUSAL TIME</span><div class="time-line">${V.versions.map((v,i)=>`<button data-replay="${v.id}" class="${selected===v.id?'active':''}"><i></i><strong>${esc(v.label)}</strong><small>${esc(v.date)}</small></button>`).join('')}</div><button class="time-open" data-nav="replay">Open replay →</button></footer>`;
  }

  function actionRail(state){
    if(!state.actionRailOpen)return `<aside class="action-rail collapsed"><button data-action="toggle-action-rail">←</button></aside>`;
    if(state.scale==='fund'){
      const sit=F.fund.situations.find(x=>x.id===state.selectedSituationId)||F.fund.situations[0];
      return `<aside class="action-rail"><header><div><span class="eyebrow">SELECTED SITUATION</span><h2>${esc(sit.company)}</h2></div><button data-action="toggle-action-rail">→</button></header>
        <div class="rail-section"><span class="action-class ${sit.action_class}">${esc(sit.action_class.replace('_',' '))}</span><h3>${esc(sit.title)}</h3><p>${esc(sit.why_now)}</p></div>
        <div class="rail-facts"><div><span>Capital</span><strong>${esc(sit.capital)}</strong></div><div><span>Deadline</span><strong>${esc(sit.deadline)}</strong></div><div><span>Owner</span><strong>${esc(sit.owner)}</strong></div><div><span>Evidence</span><strong>${esc(sit.evidence)}</strong></div></div>
        <div class="rail-section"><span class="eyebrow">WHAT THIS ROLE MUST DO</span><h3>${esc(sit.required_action)}</h3><small>${esc(sit.authority_verb)}</small>${sit.case_id==='PROJECT-KEYSTONE'?`<button class="primary wide" data-open-deal="${sit.case_id}">Open Deal World</button>`:'<button class="ghost wide" disabled>Not connected in this package</button>'}</div>
        <div class="rail-section"><span class="eyebrow">PANTA IS ALREADY DOING</span>${sit.missions.map(m=>`<div class="mission-mini"><div><strong>${esc(m.label)}</strong><small>${esc(m.state)}</small></div><span><i style="width:${m.progress}%"></i></span><b>${m.progress}%</b></div>`).join('')}</div>
      </aside>`;
    }
    return `<aside class="action-rail"><header><div><span class="eyebrow">ACTION FRONTIER</span><h2>What requires attention</h2></div><button data-action="toggle-action-rail">→</button></header>
      <div class="next-best"><span class="eyebrow">NEXT-BEST WORK</span><h3>${esc(F.deal.next_best_work.label)}</h3><p>${esc(F.deal.next_best_work.reason)}</p><dl><div><dt>Owner</dt><dd>${esc(F.deal.next_best_work.owner)}</dd></div><div><dt>Closure</dt><dd>${esc(F.deal.next_best_work.duration)}</dd></div><div><dt>Unlocks</dt><dd>${esc(F.deal.next_best_work.unlocks)}</dd></div></dl><button class="primary wide" data-nav="unknowns">Open closure plan</button></div>
      <div class="rail-section"><span class="eyebrow">PENDING REVIEW</span><button class="pending-action" data-open-scene="concentration"><i></i><span><strong>Customer concentration exception</strong><small>Offer authority becomes stale</small></span><b>→</b></button><button class="pending-action" data-open-scene="earnings"><i class="routine"></i><span><strong>Earnings basis treatment</strong><small>Professional review only</small></span><b>→</b></button></div>
      <div class="rail-section"><span class="eyebrow">OPEN BOUNDARY</span><div class="coverage-meter"><span><i style="width:73%"></i></span><strong>73% mapped</strong></div><p>Seven contracts and two reference calls remain outside the reviewed perimeter.</p></div>
    </aside>`;
  }

  function fundCommand(state){
    const ordered=[...F.fund.situations].sort((a,b)=>{
      if(state.role==='partner'){const rank={authority_decision:0,escalation_only:1,professional_review:2,notification:3};return rank[a.action_class]-rank[b.action_class]}
      const rank={professional_review:0,authority_decision:1,notification:2,escalation_only:3};return rank[a.action_class]-rank[b.action_class]
    });
    const selected=F.fund.situations.find(x=>x.id===state.selectedSituationId)||ordered[0];
    return `<section class="fund-command">
      <div class="morning-delta"><header><div><span class="eyebrow">MORNING DELTA</span><h2>Four changes since the last attested state</h2></div><span>08:35</span></header><div>${F.fund.morning_delta.map(d=>`<button data-situation="SIT-${d.case_id.replace('PROJECT-','')}" class="delta-${d.kind}"><i></i><span><strong>${esc(d.label)}</strong><small>${esc(d.detail)}</small></span></button>`).join('')}</div></div>
      <div class="fund-layout">
        <section class="situation-field"><header><div><span class="eyebrow">CAPITAL & ATTENTION FIELD</span><h2>${state.role==='partner'?'Decisions requiring authority':'Work requiring execution'}</h2></div><div class="field-legend"><span class="halo-contested">Contested</span><span class="halo-review">Review</span><span class="halo-blocked">Threshold</span></div></header>
          <div class="field-canvas">${F.fund.situations.map(s=>`<button class="situation-node ${s.position.halo} ${state.selectedSituationId===s.id?'selected':''}" style="--x:${s.position.x}%;--y:${s.position.y}%;--size:${s.position.size}px" data-situation="${s.id}"><i></i><strong>${esc(s.company)}</strong><small>${esc(s.capital)}</small></button>`).join('')}<div class="field-axis x">decision proximity →</div><div class="field-axis y">capital at stake ↑</div></div>
          <footer><strong>${esc(selected.title)}</strong><span>${esc(selected.why_now)}</span></footer>
        </section>
        <section class="situation-queue"><header><span class="eyebrow">SITUATION QUEUE</span><h2>Why these objects need attention</h2></header>${ordered.map((s,index)=>`<button data-situation="${s.id}" class="queue-row ${state.selectedSituationId===s.id?'active':''}"><span class="queue-rank">${String(index+1).padStart(2,'0')}</span><div><small>${esc(s.lifecycle)} · ${esc(s.action_class.replace('_',' '))}</small><strong>${esc(s.company)} — ${esc(s.title)}</strong><p>${esc(s.priority_reasons.join(' · '))}</p></div><b>${esc(s.deadline)}</b></button>`).join('')}</section>
      </div>
    </section>`;
  }

  function dealFacts(){return `<section class="deal-facts"><div><span>Company</span><strong>${esc(V.deal.company)}</strong><small>${esc(V.deal.archetype)}</small></div>${V.deal.facts.slice(0,6).map(([l,v])=>`<button data-open-object="${l.includes('EBITDA')?'MN-FIRM-EBITDA':l.includes('Enterprise')?'MN-EV':l.includes('debt')?'MN-DEBT':l.includes('Customer')?'CP-CONCENTRATION':'CP-BASE-RETURNS'}"><span>${esc(l)}</span><strong>${esc(v)}</strong></button>`).join('')}</section>`}
  function questionRow(question,index,state){const view=getQView(question,state);return `<button class="question-row-v17" data-question="${question.id}"><span>${String(index+1).padStart(2,'0')}</span><div><strong>${esc(question.label)}</strong><small>${esc(question.workstream)} · ${esc(question.origin.entry_type)}</small></div><div><strong>${esc(view.view)}</strong><small>${esc(view.cause)}</small></div><em class="${dispositionClass(view.display_strength)}"><i></i>${esc(view.display_strength)}</em><div><strong>${esc(view.economic_weight)}</strong><small>${(question.priority_reasons||[])[0]||'Decision relevance'}</small></div><b>${view.open_work}</b>${avatar(question.owner)}</button>`}
  function dealCommand(state){
    const ordered=(V.priority_order[state.settled?'post-cdd':'post-qoe']||V.question_spine.map(x=>x.id)).map(qBy).filter(Boolean);
    return `<section class="deal-command">
      <div class="deal-delta"><div><span class="eyebrow">DELTA SINCE LAST REVIEW</span><h2>${esc(F.deal.morning_delta.label)}</h2><p><del>${esc(F.deal.morning_delta.from)}</del><strong>${esc(F.deal.morning_delta.to)}</strong><span>${esc(F.deal.morning_delta.source)}</span></p></div><button class="primary" data-open-scene="concentration">Review material change</button></div>
      ${dealFacts()}
      <div class="deal-grid"><section class="question-spine-v17"><header><div><span class="eyebrow">UNDERWRITING QUESTION SPINE</span><h2>What are we underwriting now?</h2></div><span>Visible reasons · no opaque score</span></header><div class="question-columns"><span>#</span><span>Question</span><span>Current institutional view</span><span>Strength</span><span>Economic relevance</span><span>Work</span><span>Owner</span></div>${ordered.map((qq,i)=>questionRow(qq,i,state)).join('')}</section>
        <aside class="deal-side"><section class="case-branches"><span class="eyebrow">INSTITUTIONAL STATE</span><div><small>APPROVED</small><strong>${esc(F.deal.branches.approved)}</strong></div><div><small>CURRENT</small><strong>${esc(F.deal.branches.current)}</strong></div><div><small>WORKING</small><strong>${esc(F.deal.branches.working)}</strong></div></section><section class="command-query"><span class="eyebrow">ASK THE CASE</span><h3>Navigate by object, not folders</h3>${F.deal.command_suggestions.map(s=>`<button data-command-query="${esc(s)}">${esc(s)}<b>→</b></button>`).join('')}</section></aside>
      </div>
    </section>`;
  }

  function workView(state){
    const streams=['All',...new Set(V.question_spine.map(q=>q.workstream))];
    const qs=V.question_spine.filter(q=>state.selectedWorkstream==='All'||q.workstream===state.selectedWorkstream);
    return `<section class="work-view"><header class="page-head"><div><span class="eyebrow">DILIGENCE / WORK</span><h2>The same case, organized for execution</h2></div><nav>${streams.map(s=>`<button data-workstream="${s}" class="${state.selectedWorkstream===s?'active':''}">${esc(s)}</button>`).join('')}</nav></header><div class="work-board">${qs.map(q=>{const v=getQView(q,state);return `<article><header><div><span>${esc(q.workstream)}</span><h3>${esc(q.label)}</h3></div>${avatar(q.owner)}</header><div class="work-current"><small>CURRENT VIEW</small><strong>${esc(v.view)}</strong></div>${(q.work_plan||[]).map((w,i)=>`<button data-open-object="${q.id}"><i class="${w.status==='complete'?'done':w.status==='blocked'?'blocked':'open'}">${w.status==='complete'?'✓':i+1}</i><span><strong>${esc(w.label)}</strong><small>${esc(w.method)} · ${esc(w.owner)}</small></span><b>${esc(w.status)}</b></button>`).join('')}<footer><span>${v.open_work} open</span><strong>${esc(v.economic_weight)}</strong></footer></article>`}).join('')}</div></section>`;
  }

  function foundationsView(){const room=F.deal.rooms.foundations;return `<section class="room-view foundations-view"><header class="page-head"><div><span class="eyebrow">ROOM</span><h2>${esc(room.title)}</h2><p>${esc(room.subtitle)}</p></div><span class="room-count">${room.sets.length} minimal support sets</span></header><div class="foundation-grid">${room.sets.map(set=>`<article class="foundation-card ${set.strength}"><header><span>${esc(set.strength)}</span><strong>${esc(set.economic)}</strong></header><h3>${esc(set.label)}</h3><div class="support-floor">${set.members.map((m,i)=>`<button data-question="${set.question_id}"><i>${i+1}</i><span>${esc(m)}</span></button>`).join('')}</div><footer><button data-question="${set.question_id}">Open question →</button></footer></article>`).join('')}</div></section>`}
  function unknownsView(){const room=F.deal.rooms.unknowns;return `<section class="room-view unknowns-view"><header class="page-head"><div><span class="eyebrow">ROOM</span><h2>${esc(room.title)}</h2><p>${esc(room.subtitle)}</p></div><button class="primary" data-open-object="NBW-CONTRACTS">Dispatch next-best work</button></header><div class="unknown-list"><div class="unknown-head"><span>Rank</span><span>Unknown</span><span>Decision value</span><span>Closure path</span><span>Owner</span></div>${room.items.map(item=>`<button data-question="${item.question_id}"><b>${String(item.rank).padStart(2,'0')}</b><div><strong>${esc(item.label)}</strong><small>${esc(item.question_id)}</small></div><em>${esc(item.value)}</em><span>${esc(item.closure)}</span><span>${esc(item.owner)}</span></button>`).join('')}</div></section>`}
  function shadowICView(){const r=F.deal.rooms.shadowIC;const forItems=r.theses.filter(x=>x.side==='FOR');const against=r.theses.filter(x=>x.side==='AGAINST');const col=(title,items)=>`<section><header><span>${title}</span><b>${items.length}</b></header>${items.map(x=>`<button data-open-object="${x.id}" class="shadow-thesis ${x.strength}"><div><small>${esc(x.strength)}</small><h3>${esc(x.label)}</h3></div><ul>${x.basis.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></button>`).join('')}</section>`;return `<section class="room-view shadow-view"><header class="page-head"><div><span class="eyebrow">ROOM</span><h2>${esc(r.title)}</h2><p>${esc(r.subtitle)}</p></div>${pill('LIVE','current')}</header><div class="shadow-grid">${col('CASE FOR',forItems)}<div class="shadow-verdict"><span class="eyebrow">CURRENT SHADOW VERDICT</span><strong>${esc(r.verdict)}</strong><small>Not an authority act · continuously maintained</small><button class="gold-button" data-nav="decision">Open formal Decision Room</button></div>${col('CASE AGAINST',against)}</div></section>`}

  function artifactsView(state){const selected=artifactBy(state.selectedArtifactId)||V.artifacts[0];return `<section class="artifacts-view"><header class="page-head"><div><span class="eyebrow">ARTIFACTS</span><h2>Representations synchronized to the case</h2><p>Files remain inspectable, versioned projections. They do not silently change institutional state.</p></div><span>${V.artifacts.length} governed artifacts</span></header><div class="artifact-layout"><nav>${V.artifacts.map(a=>`<button data-artifact="${a.id}" class="${selected.id===a.id?'active':''}"><i>${a.type.includes('Excel')?'X':a.type.includes('memo')?'W':'D'}</i><span><strong>${esc(a.title)}</strong><small>${esc(a.type)} · ${esc(a.current_version)}</small></span>${pill(a.status)}</button>`).join('')}</nav><section class="artifact-preview"><header><div><span class="eyebrow">${esc(selected.type)}</span><h2>${esc(selected.title)}</h2></div><div class="button-row"><button class="ghost" data-open-object="${selected.id}">Version history</button><button class="primary" data-open-object="${selected.id}">Open binding map</button></div></header>${selected.id==='ART-MODEL'?`<div class="sheet-preview"><div class="sheet-tabs"><span>Inputs</span><span>SB_Base</span><span class="active">Ownership_Returns</span></div><table><tr><th>Metric</th><th>Current</th><th>Source</th><th>State</th></tr><tr><td>Firm EBITDA</td><td>$11.4m</td><td>Inputs!B11</td><td>${pill('Current')}</td></tr><tr><td>Base MOIC</td><td>2.00x</td><td>Ownership_Returns!K4</td><td>${pill('Current')}</td></tr><tr><td>Base IRR</td><td>14.8%</td><td>Ownership_Returns!L4</td><td>${pill('Current')}</td></tr><tr class="stale"><td>Offer ceiling</td><td>$108.0m</td><td>Offer v7</td><td>${pill('Stale')}</td></tr></table></div>`:`<div class="document-preview"><span>${esc(selected.current_version)}</span><h3>${esc(selected.title)}</h3><p>The current document remains bound to the approved and current case objects. Any material manual edit becomes a reconciliation proposal.</p><div class="doc-callout"><small>BOUND OBJECTS</small><strong>Firm EBITDA · Customer concentration · Offer authority · IC conditions</strong></div></div>`}</section></div></section>`}

  function registryView(state){return `<section class="registry-view"><header class="page-head"><div><span class="eyebrow">ROOM</span><h2>Registry</h2><p>Every source, system action, human judgment and authority act in one append-only record.</p></div><div class="registry-legend"><span class="human">Human</span><span class="system">System</span><span class="authority">Authority</span></div></header><div class="registry-table"><div class="registry-head"><span>Time</span><span>Actor</span><span>Event</span><span>Object</span></div>${[...state.history].reverse().map(ev=>`<button data-open-object="${ev.object_id||ev.id}"><span>${esc(ev.time)}</span><span class="actor-${ev.kind==='AUTHORITY'?'authority':ev.actor==='PANTA'||ev.actor.includes('Engine')||ev.actor.includes('Compiler')||ev.actor.includes('Service')?'system':'human'}">${esc(ev.actor)}</span><div><strong>${esc(ev.label)}</strong><small>${esc(ev.detail)}</small></div><code>${esc(ev.object_id||'—')}</code></button>`).join('')}</div></section>`}

  function replayView(state){const r=F.deal.replay;const selected=r.snapshots.find(x=>x.id===state.selectedReplayId)||r.snapshots[0];const lane=(title,items,cls)=>`<section class="replay-lane ${cls}"><header>${title}<b>${items.length}</b></header>${items.length?items.map(i=>`<div>${esc(i)}</div>`).join(''):'<div class="empty">None</div>'}</section>`;return `<section class="replay-view"><header class="page-head"><div><span class="eyebrow">CAUSAL REPLAY</span><h2>What was known, believed, approved and still open?</h2><p>Scrub the institutional state without rewriting history from today’s perspective.</p></div>${pill('BITEMPORAL','current')}</header><nav class="replay-timeline">${r.snapshots.map(s=>`<button data-replay="${s.id}" class="${selected.id===s.id?'active':''}"><i></i><strong>${esc(s.label)}</strong><small>${esc(s.date)}</small></button>`).join('')}</nav><div class="replay-snapshot"><header><div><span class="eyebrow">AS KNOWN ON ${esc(selected.date)}</span><h2>${esc(selected.label)}</h2></div><button class="ghost" data-action="replay-transition">Replay transition</button></header><div class="replay-lanes">${lane('KNOWN',selected.known,'known')}${lane('BELIEVED',selected.believed,'believed')}${lane('APPROVED',selected.approved,'approved')}${lane('OPEN',selected.open,'open')}</div></div></section>`}

  function scenarioView(state){const lab=F.deal.scenarioLab;const selected=lab.scenarios.find(x=>x.id===state.selectedScenarioId)||lab.scenarios[0];return `<section class="scenario-view"><header class="page-head"><div><span class="eyebrow">SPECIAL ROOM</span><h2>Scenario Lab</h2><p>Governed future branches with explicit operating mechanisms, not decorative sensitivities.</p></div><button class="ghost" data-nav="deal-command">Return to Deal World</button></header><div class="scenario-layout"><nav>${lab.scenarios.map(s=>`<button data-scenario="${s.id}" class="${selected.id===s.id?'active':''}"><i class="${s.state.toLowerCase()}"></i><span><strong>${esc(s.label)}</strong><small>${esc(s.state)}</small></span><b>${esc(s.moic)} · ${esc(s.irr)}</b></button>`).join('')}</nav><section class="trajectory"><header><div><span class="eyebrow">SELECTED BRANCH</span><h2>${esc(selected.label)}</h2></div>${pill(selected.state,selected.state==='CURRENT'?'current':'scenario')}</header><div class="trajectory-chart"><div class="axis y"><span>Economics</span></div><div class="trajectory-line"><i style="--p:8%"></i><i style="--p:31%"></i><i style="--p:52%"></i><i style="--p:73%"></i><i style="--p:94%"></i></div><div class="trajectory-labels"><span>Entry</span><span>Operations</span><span>Cash</span><span>Debt</span><span>Exit</span></div></div><div class="scenario-stats"><div><span>MOIC</span><strong>${esc(selected.moic)}</strong></div><div><span>IRR</span><strong>${esc(selected.irr)}</strong></div><div><span>Opening debt</span><strong>${esc(selected.debt)}</strong></div></div><div class="driver-list"><span class="eyebrow">MECHANISMS</span>${selected.drivers.map(d=>`<div><i></i>${esc(d)}</div>`).join('')}</div><div class="scenario-markers">${selected.markers.map(m=>`<span>${esc(m)}</span>`).join('')}</div>${selected.state==='SCENARIO'?`<button class="gold-button" data-nav="decision">Submit branch for governed promotion</button>`:'<small class="current-note">This is the Current branch. It cannot be overwritten in place.</small>'}</section></div></section>`}

  function decisionView(state){const r=F.deal.decisionRoom;return `<section class="decision-view"><header class="page-head"><div><span class="eyebrow">SPECIAL ROOM · AUTHORITY</span><h2>Decision Room</h2><p>One named request, several executable courses, one attested outcome.</p></div><button class="ghost" data-nav="deal-command">Return without deciding</button></header><div class="decision-table"><aside class="evidence-plane"><header>Evidence plane</header><section><span>SUPPORTING</span>${r.evidence_for.map(e=>`<div><i></i>${esc(e)}</div>`).join('')}</section><section class="against"><span>OPPOSING</span>${r.evidence_against.map(e=>`<div><i></i>${esc(e)}</div>`).join('')}</section></aside><main><span class="eyebrow">${esc(r.verb)}</span><h1>${esc(r.title)}</h1><div class="decision-meta"><span>${esc(r.holder)}</span><span>${esc(r.deadline)}</span><span>${esc(r.rule)}</span></div><div class="course-list">${r.courses.map(c=>`<button data-course="${c.id}" class="${state.selectedCourseId===c.id?'selected':''}"><header><i></i><strong>${esc(c.label)}</strong>${pill(c.policy,c.policy.includes('WITHIN')?'current':c.policy.includes('RISK')?'stale':'review')}</header><h3>${esc(c.economics)}</h3><ul>${c.conditions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></button>`).join('')}</div></main><aside class="authority-plane"><header>Authority plane</header><div><span>Holder</span><strong>${esc(r.holder)}</strong></div><div><span>Rule</span><strong>${esc(r.rule)}</strong></div><div><span>Snapshot</span><strong>Current · Concentration review</strong></div><div><span>New evidence</span><strong>Suspends request</strong></div></aside></div><footer class="attestation-edge"><div><span class="eyebrow">ATTESTATION EDGE</span><strong>${state.selectedCourseId?esc(r.courses.find(x=>x.id===state.selectedCourseId)?.label):'Select a course of action'}</strong></div><button class="gold-button" data-action="attest-decision" ${state.selectedCourseId?'':'disabled'}>Attest decision</button></footer></section>`}

  function executionView(state){const e=F.deal.executionRoom;return `<section class="execution-view"><header class="page-head"><div><span class="eyebrow">SPECIAL ROOM · EXTERNALITY</span><h2>Execution Room</h2><p>Authority is necessary but not sufficient: the exact external effect is controlled here.</p></div><button class="ghost" data-nav="decision">Back to authority record</button></header><div class="execution-boundary"><section class="execution-instruction"><header><div><span class="eyebrow">${esc(e.type)}</span><h2>${esc(e.subject)}</h2></div>${pill(state.executionStatus==='simulated-sent'?'SIMULATED SENT':'READY',state.executionStatus==='simulated-sent'?'current':'review')}</header><dl><div><dt>To</dt><dd>${esc(e.recipient)}</dd></div><div><dt>From</dt><dd>${esc(e.sender)}</dd></div><div><dt>Document</dt><dd>${esc(e.document)}</dd></div></dl><div class="message-paper"><p>${esc(e.message)}</p></div><div class="attachments">${e.attachments.map(a=>`<span>${esc(a)}</span>`).join('')}</div></section><aside><span class="eyebrow">PRECONDITIONS</span>${e.checks.map(c=>`<div class="execution-check"><i>✓</i><span>${esc(c)}</span></div>`).join('')}<div class="externality-warning"><strong>Externality boundary</strong><p>${esc(e.externality)}</p></div><button class="gold-button wide" data-action="execute-external" ${state.executionStatus==='sending'||state.executionStatus==='simulated-sent'?'disabled':''}>${state.executionStatus==='sending'?'Executing checks…':state.executionStatus==='simulated-sent'?'Recorded':'Approve simulated delivery'}</button></aside></div></section>`}

  function sourceArrival(event){return `<section class="arrival-view"><div class="source-orbit"><div class="orbit one"></div><div class="orbit two"></div><button data-open-object="${event.event_id}" class="source-node"><i>↘</i><span><strong>${esc(event.source_title)}</strong><small>${esc(event.locator)}</small></span></button><div class="placement"><small>PLACED UNDER</small><strong>${esc(qBy(event.scene_id==='earnings'?'UQ-EARNINGS':'UQ-REVENUE').label)}</strong></div></div><div class="arrival-copy"><span class="eyebrow">NEW EVIDENCE INTERCEPTED</span><h1>${esc(event.label)}</h1><p>PANTA placed the source in the pre-existing investment case and prepared the minimum review required before anything changes.</p><div class="dimension-chips"><span>${esc(event.definition)}</span><span>${esc(event.period)}</span><span>${esc(event.perimeter)}</span></div><button class="primary large" data-action="review-source">Review material delta</button></div></section>`}
  function evidenceReview(event){return `<section class="evidence-review"><div class="source-paper"><span class="eyebrow">EXACT SOURCE</span><h2>${esc(event.source_title)}</h2><p><mark>${esc(event.source_passage)}</mark></p><footer>${esc(event.locator)}</footer></div><div class="semantic-binding"><span class="eyebrow">SEMANTIC APPLICABILITY</span><h2>Why this belongs here</h2><dl><div><dt>Definition</dt><dd>${esc(event.definition)}</dd></div><div><dt>Period</dt><dd>${esc(event.period)}</dd></div><div><dt>Perimeter</dt><dd>${esc(event.perimeter)}</dd></div><div><dt>Question</dt><dd>${esc(qBy(event.scene_id==='earnings'?'UQ-EARNINGS':'UQ-REVENUE').label)}</dd></div></dl><div class="binding-route"><span>Source</span><i>→</i><span>Claim</span><i>→</i><span>Case Position</span><i>→</i><span>Model binding</span></div><button class="primary" data-action="prepare-treatment">Prepare professional treatment</button></div></section>`}
  function treatmentReview(event){const qid=event.scene_id==='earnings'?'UQ-EARNINGS':'UQ-REVENUE';const q=qBy(qid);const current=getQView(q,{settled:false});return `<section class="treatment-view"><header><div><span class="eyebrow">PROFESSIONAL REVIEW</span><h2>Choose the institutional treatment, not the source winner</h2></div>${pill('Candidate only','review')}</header><div class="treatment-grid"><section><small>CURRENT</small><h3>${esc(current.view)}</h3><p>${esc(current.cause)}</p></section><i>→</i><section class="proposed"><small>PROPOSED</small><h3>${esc(event.proposed_position)}</h3><p>Source remains preserved; adoption changes the Case Position, not the underlying evidence.</p></section></div><div class="treatment-controls"><button class="ghost" data-action="review-source">Return to source</button><button class="primary large" data-action="confirm-treatment">Confirm treatment and calculate consequences</button></div></section>`}
  function impactView(state){const result=state.transitionResult;const loading=!result&&!state.transitionError;return `<section class="impact-view"><header><div><span class="eyebrow">CHANGE IMPACT</span><h2>One admitted treatment, every mapped consequence</h2><p>Lines and motion follow the Transition Engine output. Unchanged objects remain visible with a reason.</p></div><div class="button-row"><button class="ghost" data-action="skip-transition">Skip</button><button class="ghost" data-action="replay-transition">Replay</button></div></header>${loading?`<div class="engine-loading"><i></i><strong>Waiting for Transition Engine…</strong><small>${esc(window.PantaIntegration.getMode())}</small></div>`:state.transitionError?`<div class="engine-error"><strong>Transition failed</strong><p>${esc(state.transitionError)}</p></div>`:`<div class="impact-track-v17">${result.affected_set.map((item,index)=>`${index?`<i class="impact-connector ${index<=state.transitionIndex?'reached':''}"></i>`:''}<button data-open-object="${item.object_id}" class="impact-node-v17 ${dispositionClass(item.disposition)} ${index<=state.transitionIndex?'reached':''} ${index===state.transitionIndex?'active':''}"><small>${esc(item.disposition)}</small><strong>${esc(item.label)}</strong><div><del>${esc(item.before||'—')}</del><b>${esc(item.after||'—')}</b></div><p>${esc(item.explanation)}</p></button>`).join('')}</div>${state.flowPhase==='impact-complete'?`<footer class="impact-done"><div><span class="eyebrow">CANDIDATE READY</span><strong>${result.affected_set.length} dispositions · ${result.human_stops.length} human stop(s) · replay ${esc(result.replay_hash)}</strong></div><button class="primary" data-action="continue-impact">Open action frontier</button></footer>`:''}`}</section>`}
  function actionFrontier(state){const result=state.transitionResult;return `<section class="action-frontier-view"><header class="page-head"><div><span class="eyebrow">ACTION FRONTIER</span><h2>Translate the Candidate into coordinated work</h2><p>The case treatment and the artifact response remain separate acts.</p></div>${pill(result.status,'review')}</header><div class="frontier-layout"><section class="change-sets"><header><h3>Prepared change sets</h3><span>${result.artifact_change_sets.length}</span></header>${result.artifact_change_sets.map(cs=>`<label><input type="checkbox" data-change-set="${cs.artifact_id}" ${state.selectedChangeSets.includes(cs.artifact_id)?'checked':''}><div><strong>${esc(cs.title)}</strong><small>${esc(cs.version_before)} → ${esc(cs.version_after)}</small></div>${pill(cs.status,'prepared')}</label>`).join('')}</section><section class="frontier-outcomes"><header><h3>What happens next</h3></header><div><span>Automatic</span><strong>Recompute mapped model values</strong><small>Already completed in Candidate</small></div><div><span>Professional</span><strong>Approve synchronized artifact changes</strong><small>${result.artifact_change_sets.length} change sets prepared</small></div>${result.human_stops.length?`<div class="human"><span>Human stop</span><strong>${esc(result.human_stops[0].authority_verb)}</strong><small>${esc(result.human_stops[0].required_role)} · ${esc(result.human_stops[0].reason)}</small></div>`:''}<div><span>Coverage</span><strong>${result.coverage_limits.length?`${result.coverage_limits.length} declared limit(s)`:'No new limit'}</strong><small>Unknowns are not silently closed</small></div></section></div><footer><button class="ghost" data-action="replay-transition">Review impact again</button><button class="primary large" data-action="prepare-response">Prepare response and route judgment</button></footer></section>`}
  function settledView(state){const s=state.settled||{};return `<section class="settled-view"><div class="settled-symbol">✓</div><span class="eyebrow">DEAL WORLD SETTLED</span><h1>The affected system is current again</h1><p>Consequences were drawn, residual uncertainty was declared, and the prior Approved snapshot remains immutable.</p><div class="settlement-stats"><div><span>Current state</span><strong>${esc(s.current_state_id||'current-demo')}</strong></div><div><span>Approved</span><strong>${s.approved_unchanged===false?'Successor created':'Unchanged'}</strong></div><div><span>Replay hash</span><strong>${esc(s.replay_hash||state.transitionResult?.replay_hash||'—')}</strong></div></div><div class="button-row"><button class="primary" data-nav="registry">Open Registry</button><button class="ghost" data-nav="replay">Open Causal Replay</button><button class="ghost" data-nav="deal-command">Return to Deal World</button></div></section>`}
  function changeView(state){const event=F.events[state.activeScene];const phases=['arrival','evidence','treatment','impact','action','decision','execution','settled'];const current=state.flowPhase==='impact-complete'?'impact':state.flowPhase;const idx=Math.max(0,phases.indexOf(current));let body='';if(state.flowPhase==='arrival')body=sourceArrival(event);else if(state.flowPhase==='evidence')body=evidenceReview(event);else if(state.flowPhase==='treatment')body=treatmentReview(event);else if(['impact','impact-complete','impact-error'].includes(state.flowPhase))body=impactView(state);else if(state.flowPhase==='action')body=actionFrontier(state);else if(state.flowPhase==='settled')body=settledView(state);else body=impactView(state);return `<section class="change-shell"><header class="flow-header"><button class="ghost" data-nav="deal-command">← Deal World</button><div>${phases.map((p,i)=>`<span class="${i<idx?'done':i===idx?'active':''}">${p}</span>`).join('')}</div><button class="ghost" data-action="reset-demo">Reset</button></header>${body}</section>`}

  function content(state){
    if(state.loading)return `<div class="loading-screen"><i></i><strong>Loading PANTA V17</strong></div>`;
    if(state.scale==='fund')return fundCommand(state);
    const map={'deal-command':dealCommand,'work':workView,'foundations':foundationsView,'unknowns':unknownsView,'shadow-ic':shadowICView,'artifacts':artifactsView,'registry':registryView,'replay':replayView,'scenario':scenarioView,'decision':decisionView,'execution':executionView,'change':changeView};
    return (map[state.view]||dealCommand)(state);
  }

  function comments(state,id){const list=state.comments[id]||[];return `<div class="comments"><span class="eyebrow">COMMENTS</span>${list.map(c=>`<div class="comment"><header><strong>${esc(c.author)}</strong><small>${esc(c.time)}</small></header><p>${esc(c.text)}</p>${c.mention?`<b>@${esc(c.mention)}</b>`:''}</div>`).join('')}<form data-comment-form="${id}"><textarea name="comment" placeholder="Attach a comment to this object"></textarea><div><select name="mention"><option value="">No mention</option><option>M. Alvarez</option><option>A. Rossi</option><option>L. Chen</option></select><button class="primary">Add</button></div></form></div>`}
  function drawerContent(state){if(!state.drawer)return '';
    const id=state.drawerId;const question=qBy(id);const artifact=artifactBy(id);const person=personBy(id);const foundation=F.deal.rooms.foundations.sets.find(x=>x.id===id);const unknown=F.deal.rooms.unknowns.items.find(x=>x.id===id);const thesis=F.deal.rooms.shadowIC.theses.find(x=>x.id===id);const transitionItem=state.transitionResult?.affected_set.find(x=>x.object_id===id);let title=question?.label||artifact?.title||person?.name||foundation?.label||unknown?.label||thesis?.label||transitionItem?.label||id;let body='';
    if(question){const v=getQView(question,state);if(state.drawerTab==='basis')body=`<span class="eyebrow">CURRENT INSTITUTIONAL VIEW</span><h3>${esc(v.view)}</h3><p>${esc(v.cause)}</p><div class="aperture-list">${(question.claim_ids||[]).map(cid=>{const c=V.canonical.claims.find(x=>x.claim_id===cid);return c?`<button data-open-object="${cid}"><strong>${esc(c.statement)}</strong><small>${esc(c.source_id)} · ${esc(c.period)}</small></button>`:''}).join('')}</div>`;else if(state.drawerTab==='dependents')body=`<span class="eyebrow">DEPENDENTS & COVERAGE</span><h3>${esc(v.economic_weight)}</h3><div class="aperture-list">${(question.model_node_ids||[]).map(mid=>`<button data-open-object="${mid}"><strong>${esc(mid)}</strong><small>Mapped financial dependency</small></button>`).join('')}</div><div class="coverage-note">Coverage is explicit; absence of a known edge is never treated as proof of completeness.</div>`;else if(state.drawerTab==='action')body=`<span class="eyebrow">CLOSURE PLAN</span><h3>${v.open_work} open item(s)</h3><div class="aperture-list">${(question.work_plan||[]).map(w=>`<div><strong>${esc(w.label)}</strong><small>${esc(w.method)} · ${esc(w.owner)} · ${esc(w.status)}</small></div>`).join('')}</div>`;else body=`<span class="eyebrow">HISTORY</span><h3>${esc(question.label)}</h3>${comments(state,id)}`;
    }else if(artifact)body=`<span class="eyebrow">ARTIFACT</span><h3>${esc(artifact.title)}</h3><p>${esc(artifact.type)} · ${esc(artifact.current_version)}</p><div class="aperture-list">${artifact.versions.map(v=>`<div><strong>${esc(v.version)}</strong><small>${esc(v.date)} · ${esc(v.cause)} · ${esc(v.status)}</small></div>`).join('')}</div>${comments(state,id)}`;
    else if(person)body=`<span class="eyebrow">PARTICIPANT</span><div class="person-title">${avatar(person,'large')}<div><h3>${esc(person.name)}</h3><p>${esc(person.role)}</p></div></div><div class="aperture-list"><div><strong>Owned</strong><small>${esc(person.owned)}</small></div><div><strong>Settled</strong><small>${esc(person.settled)}</small></div></div>`;
    else if(foundation)body=`<span class="eyebrow">MINIMAL SUPPORT SET</span><h3>${esc(foundation.label)}</h3><p>${esc(foundation.economic)}</p><div class="aperture-list">${foundation.members.map(m=>`<div><strong>${esc(m)}</strong></div>`).join('')}</div>`;
    else if(unknown)body=`<span class="eyebrow">UNKNOWN</span><h3>${esc(unknown.label)}</h3><div class="aperture-list"><div><strong>Decision value</strong><small>${esc(unknown.value)}</small></div><div><strong>Closure</strong><small>${esc(unknown.closure)}</small></div><div><strong>Owner</strong><small>${esc(unknown.owner)}</small></div></div>`;
    else if(thesis)body=`<span class="eyebrow">SHADOW IC POSITION</span><h3>${esc(thesis.label)}</h3><p>${esc(thesis.side)} · ${esc(thesis.strength)}</p><div class="aperture-list">${thesis.basis.map(b=>`<div><strong>${esc(b)}</strong></div>`).join('')}</div>`;
    else if(transitionItem)body=`<span class="eyebrow">TRANSITION OBJECT</span><h3>${esc(transitionItem.label)}</h3><div class="delta-card"><del>${esc(transitionItem.before)}</del><b>${esc(transitionItem.after)}</b></div><p>${esc(transitionItem.explanation)}</p>`;
    else body=`<span class="eyebrow">OBJECT</span><h3>${esc(id)}</h3><p>This object is available through the integration contract but has no additional demo projection.</p>${comments(state,id)}`;
    return `<header><div><span class="eyebrow">OBJECT APERTURE</span><h2>${esc(title)}</h2></div><button data-action="close-drawer">×</button></header><nav>${[['basis','Basis'],['dependents','Dependents & coverage'],['action','Action'],['history','History']].map(([id,label])=>`<button data-drawer-tab="${id}" class="${state.drawerTab===id?'active':''}">${label}</button>`).join('')}</nav><div class="drawer-body">${body}</div>`;
  }

  function commandModal(state){if(!state.commandOpen)return '';return `<div class="command-backdrop" data-action="close-command"><section class="command-palette" onclick="event.stopPropagation()"><header><span>⌘K</span><input id="command-input" value="${esc(state.commandQuery)}" placeholder="Search the live investment case" autofocus><button data-action="close-command">×</button></header><div class="command-results">${state.commandResults.length?state.commandResults.map((r,i)=>`<button data-command-index="${i}"><span>${esc(r.type)}</span><strong>${esc(r.label)}</strong><b>↵</b></button>`).join(''):`<div class="empty-state">Type a question, object or room.</div>`}</div><footer>${F.deal.command_suggestions.slice(0,3).map(s=>`<button data-command-query="${esc(s)}">${esc(s)}</button>`).join('')}</footer></section></div>`}

  function bind(state){
    document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>R.setRole(b.dataset.role));
    document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>b.dataset.scale==='fund'?R.openFund():R.openDeal());
    document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>R.navigate(b.dataset.nav));
    document.querySelectorAll('[data-open-deal]').forEach(b=>b.onclick=()=>R.openDeal(b.dataset.openDeal));
    document.querySelectorAll('[data-situation]').forEach(b=>b.onclick=()=>R.setSituation(b.dataset.situation));
    document.querySelectorAll('[data-question]').forEach(b=>b.onclick=e=>{if(e.target.closest('button')!==b&&e.target.closest('button'))return;R.setQuestion(b.dataset.question,true)});
    document.querySelectorAll('[data-workstream]').forEach(b=>b.onclick=()=>R.setWorkstream(b.dataset.workstream));
    document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=()=>R.setArtifact(b.dataset.artifact));
    document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>R.setScenario(b.dataset.scenario));
    document.querySelectorAll('[data-replay]').forEach(b=>b.onclick=()=>{R.setReplay(b.dataset.replay);if(state.view!=='replay')R.navigate('replay')});
    document.querySelectorAll('[data-open-object]').forEach(b=>b.onclick=e=>{e.stopPropagation();R.openDrawer('object',b.dataset.openObject,'basis')});
    document.querySelectorAll('[data-open-scene]').forEach(b=>b.onclick=()=>R.openScene(b.dataset.openScene));
    document.querySelectorAll('[data-drawer-tab]').forEach(b=>b.onclick=()=>R.setDrawerTab(b.dataset.drawerTab));
    document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>R.selectCourse(b.dataset.course));
    document.querySelectorAll('[data-change-set]').forEach(b=>b.onchange=()=>R.toggleChangeSet(b.dataset.changeSet));
    document.querySelectorAll('[data-command-query]').forEach(b=>b.onclick=()=>R.command(b.dataset.commandQuery));
    document.querySelectorAll('[data-command-index]').forEach(b=>b.onclick=()=>R.openCommandResult(state.commandResults[Number(b.dataset.commandIndex)]));
    document.querySelectorAll('[data-lens]').forEach(s=>s.onchange=()=>R.setLens(s.value));
    document.querySelectorAll('[data-comment-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);if(R.addComment(f.dataset.commentForm,fd.get('comment'),fd.get('mention'))){f.reset();R.showToast('Comment attached.')}});
    document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>{const a=b.dataset.action;if(a==='open-fund')R.openFund();else if(a==='toggle-motion')R.setReducedMotion();else if(a==='toggle-action-rail')R.toggleActionRail();else if(a==='open-command')R.command('');else if(a==='close-command')R.closeCommand();else if(a==='close-drawer')R.closeDrawer();else if(a==='review-source')R.reviewSource();else if(a==='prepare-treatment')R.prepareTreatment();else if(a==='confirm-treatment')R.confirmTreatment();else if(a==='skip-transition')R.skipTransition();else if(a==='replay-transition')R.replayTransition();else if(a==='continue-impact')R.continueFromImpact();else if(a==='prepare-response')R.prepareResponse();else if(a==='attest-decision')R.attestDecision();else if(a==='execute-external')R.executeExternal();else if(a==='reset-demo')R.reset();});
    const input=document.getElementById('command-input');if(input){input.oninput=()=>R.command(input.value);setTimeout(()=>input.focus(),0)}
  }

  function render(state){
    app.innerHTML=`<div class="v17-shell ${state.actionRailOpen?'with-action':'without-action'}">${contextRail(state)}<section class="workspace">${objectiveHeader(state)}<main class="workspace-content lens-${state.lens}">${content(state)}</main>${causalTimeRail(state)}</section>${actionRail(state)}</div>`;
    drawer.innerHTML=drawerContent(state);drawer.className=`object-drawer ${state.drawer?'open':''}`;
    modal.innerHTML=commandModal(state);modal.className=`modal-root ${state.commandOpen?'open':''}`;
    toast.textContent=state.toast||'';toast.className=`toast ${state.toast?'show':''}`;
    document.body.classList.toggle('reduced-motion',state.reducedMotion);
    document.body.dataset.view=state.view;
    bind(state);
  }
  R.subscribe(render);
  window.addEventListener('keydown',event=>{
    if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();R.command('')}
    if(event.key==='Escape'){R.closeCommand();R.closeDrawer()}
    if(event.shiftKey&&event.key.toLowerCase()==='t')window.PantaSelfTest?.open();
  });
})();
