(function(){
  'use strict';
  const S=window.PantaStore;
  const controllers=new Map();
  const encoder=new TextEncoder();
  const uid=prefix=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
  async function jsonHash(value){const raw=encoder.encode(JSON.stringify(value));if(crypto?.subtle){const digest=await crypto.subtle.digest('SHA-256',raw);return'sha256:'+Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('')}return`sha256:local-${raw.length}`}
  function abort(key){controllers.get(key)?.abort();controllers.delete(key)}
  async function request(path,options={},key='default'){
    abort(key);const controller=new AbortController();controllers.set(key,controller);const st=S.get();const headers={...(options.headers||{})};if(!(options.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';if(st.sessionId)headers['X-Panta-Session']=st.sessionId;
    let response;try{response=await fetch(`${st.apiBase}${path}`,{...options,headers,signal:controller.signal})}finally{controllers.delete(key)}
    const type=response.headers.get('content-type')||'';let body={};if(type.includes('application/json')){try{body=await response.json()}catch(_){body={}}}else body=await response.text();
    if(!response.ok){const raw=body?.error||body||{};const e=new Error(raw.message||String(body)||`${response.status} ${response.statusText}`);e.code=raw.code||'API_ERROR';e.details=raw.details||{};e.status=response.status;throw e}return body
  }
  function localIndex(projection,q){
    const term=(q||'').trim().toLowerCase();const items=[];
    (window.PantaConstants?.rooms||[]).filter(r=>r.persistent).forEach(r=>items.push({id:r.id,type:'ROOM',label:r.label,route:r.id,search_text:r.label}));
    (projection?.deal?.question_spine||[]).forEach(x=>items.push({id:x.id,type:'QUESTION',label:x.label,route:'deal-command',search_text:`${x.label} ${x.workstream||''} ${(x.priority_reasons||[]).join(' ')}`}));
    (projection?.deal?.artifacts||[]).forEach(x=>{items.push({id:x.id,type:'ARTIFACT',label:x.title,route:'artifacts',search_text:`${x.title} ${x.type||''} ${x.file_name||''}`});(x.cell_index||[]).forEach(c=>items.push({id:c.id,type:'CELL',label:`${c.sheet}!${c.cell} — ${c.label}`,route:'artifacts',search_text:`${c.sheet} ${c.cell} ${c.label} ${c.value??''} ${c.formula||''} ${c.semantic_concept||''} ${c.period||''} ${c.perimeter||''}`}))});
    (projection?.deal?.claims||[]).forEach(x=>items.push({id:x.id,type:'CLAIM',label:x.label||x.statement?.slice(0,80)||x.id,route:'deal-command',search_text:`${x.label||''} ${x.statement||''} ${x.locator||''} ${x.period||''} ${x.perimeter||''}`}));
    (projection?.deal?.rooms?.unknowns?.items||[]).forEach(x=>items.push({id:x.id,type:'UNKNOWN',label:x.label,route:'unknowns',search_text:`${x.label} ${x.owner||''} ${x.closure||''}`}));
    (projection?.deal?.rooms?.pipeline_review?.items||[]).forEach(x=>items.push({id:x.id,type:'PIPELINE_REVIEW',label:x.label,route:'unknowns',search_text:`${x.label} ${x.stage||''} ${x.fix||''}`}));
    (projection?.deal?.interactions||[]).forEach(x=>items.push({id:x.interaction_id||x.id,type:'INTERACTION',label:x.title,route:'sources',search_text:`${x.title} ${x.interaction_type||''} ${(x.participant_ids||[]).join(' ')}`}));
    (projection?.deal?.utterances||[]).forEach(x=>items.push({id:x.utterance_id||x.id,type:'UTTERANCE',label:(x.normalized_text||x.verbatim_text||'').slice(0,90),route:'sources',search_text:`${x.verbatim_text||''} ${x.speaker_id||''} ${x.locator||''}`}));
    (projection?.deal?.discrepancy_candidates||[]).forEach(x=>items.push({id:x.discrepancy_id||x.id,type:'DISCREPANCY',label:x.label,route:'sources',search_text:`${x.label} ${x.type||''} ${x.definition_id||''}`}));
    (projection?.deal?.derivations||[]).forEach(x=>items.push({id:x.derivation_id||x.id,type:'DERIVATION',label:x.label,route:'sources',search_text:`${x.label} ${x.formula||''} ${x.value??''} ${x.unit||''}`}));
    (projection?.deal?.hypotheses||[]).forEach(x=>items.push({id:x.hypothesis_id||x.id,type:'HYPOTHESIS',label:x.label,route:'sources',search_text:`${x.label} ${x.discrepancy_id||''}`}));
    (projection?.deal?.agent_missions||[]).forEach(x=>items.push({id:x.mission_id||x.id,type:'AGENT_MISSION',label:x.label,route:'work',search_text:`${x.label} ${x.objective||''} ${x.mission_type||''}`}));
    (projection?.deal?.spine_change_proposals||[]).forEach(x=>items.push({id:x.proposal_id||x.id,type:'SPINE_CHANGE',label:x.label,route:'sources',search_text:`${x.label} ${x.reason||''}`}));
    (projection?.deal?.validation_envelopes||[]).forEach(x=>items.push({id:x.validation_envelope_id||x.id,type:'VALIDATION_ENVELOPE',label:x.label,route:'foundations',search_text:`${x.label} ${x.target_class||''} ${x.environment||''}`}));
    (projection?.deal?.command_index||[]).forEach(x=>items.push(x));const unique=[...new Map(items.map(x=>[`${x.type}:${x.id}`,x])).values()];
    return unique.filter(x=>!term||`${x.label} ${x.type} ${x.search_text||''}`.toLowerCase().includes(term)).slice(0,50)
  }
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error(`Could not load ${src}`));document.head.appendChild(s)})}
  async function ensureOfflineFixture(){if(window.PANTA_OFFLINE_FIXTURE)return window.PANTA_OFFLINE_FIXTURE;const params=new URLSearchParams(location.search),cid=params.get('case');if(!cid)throw Object.assign(new Error('Offline Demo requires an explicit case fixture.'),{code:'FIXTURE_REQUIRED'});await loadScript(`../../09_DEMO/fixture_packs/${encodeURIComponent(cid)}/offline_fixture.js`);if(!window.PANTA_OFFLINE_FIXTURE)throw new Error('Offline fixture did not register.');return window.PANTA_OFFLINE_FIXTURE}
  function offlineContext(f){const p=f.projection,ctx={...(p.context||{})};ctx.mode='OFFLINE_DEMO';ctx.action_capability='READ_ONLY';ctx.synthetic=true;ctx.no_external_effects=true;ctx.demo_session_id=`OFFLINE-${Date.now()}`;ctx.case_id=p.deal.case_id;ctx.projection_id=p.deal.projection_id||'OFFLINE-PROJECTION';ctx.projection_hash='sha256:offline-fixture';ctx.as_of_state_id=p.deal.as_of_state_id;ctx.as_of_date=p.deal.as_of_date;ctx.authenticated_actor=ctx.authenticated_actor||{actor_id:'OFFLINE-OBSERVER',name:'Offline observer',role:'Observer'};ctx.viewer_projection=ctx.viewer_projection||'associate';ctx.authority_assignments=[];ctx.contract_version='20.0';ctx.active_lens_id=p.deal.active_lens_id||p.deal.default_lens_id||p.deal.lenses?.[0]?.lens_id||null;return ctx}
  const copy=value=>value==null?value:JSON.parse(JSON.stringify(value));
  function parseCutoff(value){if(!value)return new Date('9999-12-31T23:59:59.999Z');const text=String(value);const d=/^\d{4}-\d{2}-\d{2}$/.test(text)?new Date(`${text}T23:59:59.999Z`):new Date(text);if(Number.isNaN(d.getTime()))throw Object.assign(new Error(`Invalid as-of date: ${value}`),{code:'INVALID_TEMPORAL_QUERY'});return d}
  function knownBy(item,cutoff){const value=item?.known_at||item?.timestamp||item?.created_at||item?.ingested_at;if(!value)return false;const d=new Date(value);return !Number.isNaN(d.getTime())&&d<=cutoff}
  function deriveReplaySnapshots(registry,cutoff=parseCutoff(null)){const events=copy(registry||[]).filter(e=>e.effective_date&&e.known_at&&knownBy(e,cutoff)).sort((a,b)=>String(a.known_at).localeCompare(String(b.known_at))||String(a.event_id).localeCompare(String(b.event_id)));const state={known:[],believed:[],approved:[],open:[]};return events.map((e,index)=>{const kind=String(e.kind||'').toUpperCase(),summary=e.label||e.detail||e.event_id;if(['SOURCE','INGEST','INGEST_REQUESTED','COMPILER','ORIGIN'].includes(kind))state.known.push(summary);else if(['AUTHORITY','IC_RECORD','DECISION'].includes(kind))state.approved.push(summary);else if(['COVERAGE','BLOCK','HUMAN_STOP'].includes(kind))state.open.push(summary);else state.believed.push(summary);return{id:e.result_state_id||`STATE-${e.event_id}`,event_id:e.event_id,date:e.effective_date,effective_date:e.effective_date,known_at:e.known_at,label:summary,known:state.known.slice(-4),believed:state.believed.slice(-4),approved:state.approved.slice(-4),open:state.open.slice(-4),event_index:index+1,derived_from_event_log:true,stable_hash:`sha256:event-${e.event_id}`}})}
  function deriveTemporalProjection(f,asOfDate){const allRegistry=copy(f.registry||[]),latest=[...allRegistry].sort((a,b)=>String(b.known_at||'').localeCompare(String(a.known_at||'')))[0],date=asOfDate||f.projection?.deal?.as_of_date||(latest?.known_at||'').slice(0,10);const cutoff=parseCutoff(date),p=copy(f.projection),d=p.deal;d.claims=(d.claims||[]).filter(x=>knownBy(x,cutoff));if(p.v16?.canonical?.claims)p.v16.canonical.claims=p.v16.canonical.claims.filter(x=>knownBy(x,cutoff));if(d.source_center?.sources)d.source_center.sources=d.source_center.sources.filter(x=>knownBy(x,cutoff)).map(x=>({...x,versions:(x.versions||[]).filter(v=>knownBy(v,cutoff))}));p.events=Object.fromEntries(Object.entries(p.events||{}).filter(([,v])=>knownBy(v,cutoff)));const registry=allRegistry.filter(x=>knownBy(x,cutoff)),snapshots=deriveReplaySnapshots(allRegistry,cutoff);d.replay={...(d.replay||{}),source:'REGISTRY_EVENTS',hand_authored_snapshots:false,snapshots};d.as_of_date=date;const stateEvents=registry.filter(x=>x.result_state_id).sort((a,b)=>String(a.known_at||'').localeCompare(String(b.known_at||'')));d.as_of_state_id=stateEvents.at(-1)?.result_state_id||d.initial_as_of_state_id||d.as_of_state_id||`STATE-ORIGIN-${date}`;d.projection_id=`PROJ-ASOF-${date}`;d.temporal={...(d.temporal||{}),basis:'KNOWN_AT',effective_axis:'effective_date',knowledge_axis:'known_at',replay_source:'REGISTRY_EVENTS',available_dates:[...new Set([...allRegistry.map(x=>(x.known_at||'').slice(0,10)),...(f.projection?.deal?.claims||[]).map(x=>(x.known_at||'').slice(0,10))].filter(Boolean))].sort()};return{projection:p,registry}}
  function capability(message){const e=new Error(message);e.code='CAPABILITY_UNAVAILABLE';return e}
  const offline={
    async bootstrap(){const f=await ensureOfflineFixture();return{session_id:offlineContext(f).demo_session_id,context:offlineContext(f),available_cases:[f.manifest?.case_id||f.projection.deal.case_id]}},
    async loadProjection(caseId,runId,asOfDate){const f=await ensureOfflineFixture(),derived=deriveTemporalProjection(f,asOfDate),ctx={...offlineContext(f),as_of_state_id:derived.projection.deal.as_of_state_id,as_of_date:derived.projection.deal.as_of_date,projection_id:derived.projection.deal.projection_id};return{...derived,context:ctx}},
    async search(q){const f=await ensureOfflineFixture();return{results:localIndex(f.projection,q)}},
    async getObject(id){const f=await ensureOfflineFixture();return{object:localObject(f.projection,id)}},
    async listSources(){const f=await ensureOfflineFixture();return{sources:f.projection.deal.source_center?.sources||[]}},async listInbox(){return{items:[]}},
    async ingest(){throw capability('Offline Demo is read-only. Open Mock Connected or Connected mode to ingest sources.')},async getJob(){throw capability('Offline Demo has no ingest jobs.')},async admitEvidence(){throw capability('Offline Demo cannot admit evidence.')},async removeSource(){throw capability('Offline Demo is immutable.')},
    async addNote(note){return{status:'LOCAL_ONLY',note:{...note,server_ack_at:null}}},async openDeal(){throw capability('Offline Demo cannot create a deal.')},async recordIC(){throw capability('Offline Demo cannot write an IC record.')},
    async admitEvent(eventId,payload){const f=await ensureOfflineFixture();const key=Object.keys(f.projection.events||{}).find(k=>f.projection.events[k].event_id===eventId)||Object.keys(f.transitions||{})[0];const transition=structuredClone(f.transitions[key]);transition.run_id=uid('OFFLINE-RUN');transition.candidate_state_id=uid('OFFLINE-CAND');transition.prior_state_id=f.projection.deal.as_of_state_id;return{run:{run_id:transition.run_id,status:'OFFLINE_PREVIEW'},transition,context:{...offlineContext(f),run_id:transition.run_id,candidate_state_id:transition.candidate_state_id,human_stop_id:transition.human_stops?.[0]?.stop_id||null},registry:[]}},
    async listGraphVersions(){const f=await ensureOfflineFixture();return{case_id:f.projection.deal.case_id,versions:f.projection.deal.graph_versions||[]}},
    async getGraphVersion(versionId){const f=await ensureOfflineFixture(),version=(f.projection.deal.graph_versions||[]).find(x=>x.version_id===versionId);if(!version)throw capability('This graph version is not available in the offline fixture.');const graph=version.kind==='CANDIDATE'?f.projection.deal.candidate_graph:f.projection.deal.current_graph;return{...copy(version),graph:copy(graph||{})}},
    async prepareRun(){throw capability('Offline Demo cannot prepare institutional changes.')},async attest(){throw capability('Offline Demo does not create authority records.')},async createPackage(){throw capability('Offline Demo does not create execution packages.')},async sendPackage(){throw capability('Offline Demo has no external effects.')},async settle(){throw capability('Offline Demo does not mutate institutional state.')},
    async replay(value){const f=await ensureOfflineFixture(),isDate=/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')),targetEvent=isDate?null:(f.registry||[]).find(e=>e.event_id===value),date=isDate?value:(targetEvent?.known_at||f.projection.deal.as_of_date).slice(0,10),derived=deriveTemporalProjection(f,date),snapshot=targetEvent?derived.projection.deal.replay.snapshots.find(x=>x.event_id===targetEvent.event_id):derived.projection.deal.replay.snapshots.at(-1),event=targetEvent||(f.registry||[]).find(e=>e.event_id===snapshot?.event_id);if(!snapshot||!event)throw Object.assign(new Error('No event was known by the requested date.'),{code:'REPLAY_EMPTY'});return{snapshot,event,source_state_id:event.source_state_id||snapshot.id,result_state_id:event.result_state_id||snapshot.id,stable_hash:await jsonHash(event),effective_date:event.effective_date,known_at:event.known_at,as_of_date:date,read_only:true,derived_from_event_log:true}},
    async prepareWork(workId,payload){return{draft:{draft_id:uid('OFFLINE-DRAFT'),work_item_id:workId,status:'DRAFT',...payload,synthetic:true},message:'Draft prepared locally. It has not been dispatched.'}},
    async compilerProposals(){const f=await ensureOfflineFixture();return{discrepancies:f.projection.deal.discrepancy_candidates||[],derivations:f.projection.deal.derivations||[],hypotheses:f.projection.deal.hypotheses||[],spine_changes:f.projection.deal.spine_change_proposals||[]}},
    async reviewCompilerProposal(){throw capability('Offline Demo cannot write professional compiler reviews.')},
    async prepareMission(id,payload={}){return{mission_run:{mission_run_id:uid('OFFLINE-MISSION-DRAFT'),mission_id:id,status:'PREPARED',...payload,synthetic:true,no_external_effects:true},message:'Mission draft prepared locally. Nothing was run or dispatched.'}},
    async runMission(){throw capability('Offline Demo cannot execute missions. Open Mock Connected mode for an explicit synthetic mission result.')},async newSession(){return{session_id:`OFFLINE-${Date.now()}`}}
  };
  function localObject(p,id){if(!p||!id)return null;const d=p.deal||{},lists=[d.question_spine,d.artifacts,d.claims,d.positions,d.model_nodes,d.cells,d.source_center?.sources,d.rooms?.unknowns?.items,d.source_center?.pipeline_issues,d.rooms?.shadowIC?.theses,d.rooms?.foundations?.sets,d.participants,d.interactions,d.utterances,d.discrepancy_candidates,d.derivations,d.hypotheses,d.agent_missions,d.spine_change_proposals,d.validation_envelopes,d.lenses];for(const list of lists||[]){const x=(list||[]).find(o=>[o.id,o.claim_id,o.position_id,o.model_node_id,o.cell_id,o.source_id,o.issue_id,o.participant_id,o.interaction_id,o.utterance_id,o.discrepancy_id,o.derivation_id,o.hypothesis_id,o.mission_id,o.proposal_id,o.validation_envelope_id,o.lens_id].includes(id));if(x)return x}for(const a of d.artifacts||[]){const c=(a.cell_index||[]).find(x=>[x.id,x.cell_id,x.model_node_id].includes(id));if(c)return c}return null}
  const remote={
    async bootstrap(caseId,actor){const q=new URLSearchParams();if(caseId)q.set('case_id',caseId);if(actor)q.set('actor',actor);if(S.get().sessionId)q.set('session_id',S.get().sessionId);q.set('mode',S.get().mode==='mock'?'MOCK_CONNECTED':'CONNECTED');return request(`/bootstrap?${q}`)},
    async loadProjection(caseId,runId,asOf){const q=new URLSearchParams();if(S.get().sessionId)q.set('session_id',S.get().sessionId);if(runId)q.set('run_id',runId);if(asOf)q.set('as_of_date',asOf);if(S.get().selectedLensId)q.set('lens_id',S.get().selectedLensId);return request(`/cases/${encodeURIComponent(caseId)}/projection?${q}`,{},'projection')},
    async search(q){return request(`/cases/${encodeURIComponent(S.get().caseId)}/search?${new URLSearchParams({session_id:S.get().sessionId||'',q:q||''})}`,{},'search')},
    async getObject(id){return request(`/cases/${encodeURIComponent(S.get().caseId)}/objects/${encodeURIComponent(id)}?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},`object:${id}`)},
    async listSources(){return request(`/cases/${encodeURIComponent(S.get().caseId)}/sources?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},'sources')},
    async listInbox(){return request(`/cases/${encodeURIComponent(S.get().caseId)}/inbox?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},'inbox')},
    async ingest(form){const ikey=form.idempotency_key||uid('INGEST');let body,extra={};if(form.file instanceof File){const fd=new FormData();fd.append('file',form.file,form.file_name||form.file.name||'upload');fd.append('purpose',form.purpose||'');fd.append('idempotency_key',ikey);body=fd}else{body=JSON.stringify(form);extra={'Content-Type':'application/json'}}return request(`/cases/${encodeURIComponent(S.get().caseId)}/ingest?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body,headers:{'Idempotency-Key':ikey,...extra}},'ingest')},
    async getJob(jobId){return request(`/jobs/${encodeURIComponent(jobId)}?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},`job:${jobId}`)},
    async admitEvidence(jobId,payload){return request(`/cases/${encodeURIComponent(S.get().caseId)}/ingest/${encodeURIComponent(jobId)}/admit?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},`evidence-admission:${jobId}`)},
    async removeSource(sourceId){return request(`/cases/${encodeURIComponent(S.get().caseId)}/sources/${encodeURIComponent(sourceId)}/remove?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:'{}'},`remove:${sourceId}`)},
    async addNote(note){return request(`/cases/${encodeURIComponent(S.get().caseId)}/notes?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(note)},'note')},
    async openDeal(payload){return request('/open-deal',{method:'POST',body:JSON.stringify({...payload,session_id:S.get().sessionId})},'open-deal')},
    async recordIC(payload){return request(`/cases/${encodeURIComponent(S.get().caseId)}/ic-record?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},'ic-record')},
    async admitEvent(eventId,payload){return request(`/cases/${encodeURIComponent(S.get().caseId)}/events/${encodeURIComponent(eventId)}/admit?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload),headers:{'Idempotency-Key':payload.idempotency_key}},'admission')},
    async listGraphVersions(){return request(`/cases/${encodeURIComponent(S.get().caseId)}/graph-versions?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},'graph-versions')},
    async getGraphVersion(versionId){return request(`/cases/${encodeURIComponent(S.get().caseId)}/graph-versions/${encodeURIComponent(versionId)}?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{},`graph-version:${versionId}`)},
    async prepareRun(runId,ids){return request(`/runs/${encodeURIComponent(runId)}/prepare?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify({selected_change_ids:ids})},'prepare')},
    async attest(runId,payload){return request(`/runs/${encodeURIComponent(runId)}/authority/attest?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload),headers:{'Idempotency-Key':payload.idempotency_key}},'attest')},
    async createPackage(runId){return request(`/runs/${encodeURIComponent(runId)}/execution-packages?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:'{}'},'package')},
    async sendPackage(packageId,simulateFailure=false){return request(`/execution-packages/${encodeURIComponent(packageId)}/send?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify({simulate_failure:simulateFailure})},'send')},
    async settle(runId,payload){return request(`/runs/${encodeURIComponent(runId)}/settle?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload),headers:{'Idempotency-Key':payload.idempotency_key}},'settle')},
    async replay(value){const params={session_id:S.get().sessionId||''};if(/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))params.as_of_date=value||'';else params.event_id=value||'';return request(`/cases/${encodeURIComponent(S.get().caseId)}/replay?${new URLSearchParams(params)}`,{},'replay')},
    async prepareWork(workId,payload){return request(`/cases/${encodeURIComponent(S.get().caseId)}/work-items/${encodeURIComponent(workId)}/prepare?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},'work')},
    async compilerProposals(){return request(`/cases/${encodeURIComponent(S.get().caseId)}/compiler-proposals?${new URLSearchParams({session_id:S.get().sessionId||'',lens_id:S.get().selectedLensId||''})}`,{},'compiler-proposals')},
    async reviewCompilerProposal(kind,id,payload){return request(`/cases/${encodeURIComponent(S.get().caseId)}/compiler-proposals/${encodeURIComponent(kind)}/${encodeURIComponent(id)}/review?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},`compiler-review:${id}`)},
    async prepareMission(id,payload={}){return request(`/cases/${encodeURIComponent(S.get().caseId)}/missions/${encodeURIComponent(id)}/prepare?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},`mission-prepare:${id}`)},
    async runMission(id,payload={}){return request(`/cases/${encodeURIComponent(S.get().caseId)}/missions/${encodeURIComponent(id)}/run?${new URLSearchParams({session_id:S.get().sessionId||''})}`,{method:'POST',body:JSON.stringify(payload)},`mission-run:${id}`)},
    async newSession(caseId,actor){return request('/sessions',{method:'POST',body:JSON.stringify({case_id:caseId,actor:actor||'partner',mode:S.get().mode==='mock'?'MOCK_CONNECTED':'CONNECTED'})},'new-session')}
  };
  function adapter(){return S.get().mode==='offline'?offline:remote}
  window.PantaApi={adapter,offline,remote,abort,uid,jsonHash,localIndex,localObject,deriveReplaySnapshots,deriveTemporalProjection};
})();
