(function(){
  'use strict';
  const S=window.PantaStore,C=window.PantaContracts,PA=window.PantaProjectionAdapter,API=window.PantaApi,K=window.PantaConstants;
  const clone=v=>S.clone(v);
  let transitionTimer=null,ingestTimer=null,requestEpoch=0;
  const now=()=>new Date().toISOString();
  const status=(message)=>{S.set({statusMessage:message});document.getElementById('status-region').textContent=message;setTimeout(()=>{if(S.get().statusMessage===message)S.set({statusMessage:''})},2600)};
  const toast=(message,type='info')=>{S.set({toast:{message,type}});setTimeout(()=>{if(S.get().toast?.message===message)S.set({toast:null})},3200)};
  const actor=()=>S.get().context?.authenticated_actor||{actor_id:'UNAUTHENTICATED',name:'Unauthenticated',role:'Observer'};
  const projection=()=>S.get().projection;
  const activeEvent=()=>{const p=projection(),id=S.get().activeEventId;return Object.values(p?.events||{}).find(e=>e.event_id===id)||(p?.events&&Object.values(p.events)[0])||null};
  const authorityLevel=()=>S.get().context?.authority_assignments?.find(x=>x.actor_id===actor().actor_id)?.authority_level||'NONE';
  const rank={NONE:0,PROFESSIONAL_REVIEW:1,PRINCIPAL:2,DEAL_PARTNER:3,INVESTMENT_COMMITTEE:4};
  const hasAuthority=required=>(rank[authorityLevel()]||0)>=(rank[required]||99);
  const uid=prefix=>API.uid(prefix);

  function normalizePayload(raw){
    const p=raw.projection||raw.frontend_projection||raw;
    const context={...(raw.context||p.context||{})};
    p.context=context;
    const val=C.safe(C.validateProjection,p);if(!val.ok){const e=new Error('Projection failed the V20 boundary contract.');e.code='UNSUPPORTED_PROJECTION';e.details=val.errors;throw e}
    return {projection:p,context,registry:raw.registry||p.deal.registry||[]};
  }
  function applyProjection(raw,{preserveView=true}={}){
    const {projection:p,context,registry}=normalizePayload(raw);const st=S.get(),focus=p.initial_focus||{};
    const next={projection:p,context,caseId:p.deal.case_id,registry:clone(registry),availableCapabilities:p.deal.capabilities||p.deal.navigation_capabilities||{},lastRefreshAt:now(),boot:'ready',busy:false,lastError:null,
      viewerProjection:context.viewer_projection||st.viewerProjection||'associate',selectedSituationId:st.selectedSituationId||focus.situation_id||p.fund?.situations?.[0]?.id||null,
      selectedQuestionId:st.selectedQuestionId||focus.question_id||p.deal.question_spine?.[0]?.id||null,selectedArtifactId:st.selectedArtifactId||focus.artifact_id||p.deal.artifacts?.[0]?.id||null,
      selectedScenarioId:st.selectedScenarioId||focus.scenario_id||p.deal.scenarioLab?.scenarios?.[0]?.id||null,selectedReplayId:st.selectedReplayId||focus.replay_id||p.deal.replay?.snapshots?.at(-1)?.event_id||null,selectedAsOfDate:context.as_of_date||p.deal.as_of_date||st.selectedAsOfDate||null,selectedLensId:context.active_lens_id||p.deal.active_lens_id||p.deal.default_lens_id||st.selectedLensId||null,activeEventId:st.activeEventId||(p.deal.primary_event_key&&p.events?.[p.deal.primary_event_key]?.event_id)||Object.values(p.events||{})[0]?.event_id||null};
    if(!preserveView)Object.assign(next,{view:focus.view||'fund-command',scale:(focus.view||'fund-command')==='fund-command'?'fund':'deal'});
    S.set(next);syncRoute();return p;
  }
  function modeQuery(mode=S.get().mode){return mode==='mock'?'mock':mode==='offline'?'offline':'connected'}
  function syncRoute(){const st=S.get(),q=new URLSearchParams();if(st.caseId)q.set('case',st.caseId);q.set('view',st.view);if(st.drawerObjectId)q.set('object',st.drawerObjectId);if(st.context?.as_of_date)q.set('as_of_date',st.context.as_of_date);if(st.activeRun?.run_id)q.set('run',st.activeRun.run_id);history.replaceState(null,'',`${location.pathname}${location.search}#${q}`)}
  function readRoute(){const x=Object.fromEntries(new URLSearchParams(location.hash.replace(/^#/,'')));return x}

  async function boot(){
    const st=S.get();if(st.mode==='empty'){S.set({boot:'ready',projection:null,context:{mode:'EMPTY_SYSTEM',action_capability:'READ_ONLY',synthetic:false},busy:false});return}
    S.set({boot:'loading',busy:true,operation:'BOOTSTRAP'});const initialRoute=readRoute();try{const api=API.adapter(),b=await api.bootstrap(st.caseId,new URLSearchParams(location.search).get('actor')||'partner');if(b.session_id){sessionStorage.setItem('panta-v20-session',b.session_id);S.set({sessionId:b.session_id})}S.set({availableCases:b.available_cases||b.cases||[]});const raw=await api.loadProjection(st.caseId||b.context?.case_id||b.available_cases?.[0]);applyProjection(raw,{preserveView:false});const route=initialRoute;if(route.view)S.set({view:route.view,scale:route.view==='fund-command'?'fund':'deal'});if(route.object)S.set({drawerObjectId:route.object});if(route.as_of_date)await setAsOfDate(route.as_of_date);await Promise.allSettled([refreshSources(),refreshInbox()]);status(`${b.context?.mode||st.mode} projection loaded`)}catch(e){S.set({boot:'error',busy:false,lastError:errorShape(e),error:errorShape(e)});throw e}}
  const errorShape=e=>({code:e.code||'APPLICATION_ERROR',message:e.message||String(e),details:e.details||{},status:e.status||null});
  async function refreshProjection({asOfDate=null,preserveView=true}={}){const epoch=++requestEpoch;S.set({busy:true,operation:'REFRESH'});try{const raw=await API.adapter().loadProjection(S.get().caseId,S.get().activeRun?.run_id,asOfDate);if(epoch!==requestEpoch)return;applyProjection(raw,{preserveView});status('Projection refreshed from the authoritative source')}catch(e){if(epoch===requestEpoch)S.set({busy:false,lastError:errorShape(e)});throw e}}
  async function setAsOfDate(value){if(!value)return;await refreshProjection({asOfDate:value});S.set(st=>({selectedAsOfDate:value,selectedReplayId:st.projection?.deal?.replay?.snapshots?.at(-1)?.event_id||null}));syncRoute()}
  const setAsOfState=setAsOfDate;
  async function openCase(caseId){if(!caseId)return;if(caseId!==S.get().caseId){const q=new URLSearchParams(location.search);q.set('mode',modeQuery());q.set('case',caseId);if(S.get().sessionId)q.set('session',S.get().sessionId);location.search='?'+q.toString();return}S.set({scale:'deal',view:'deal-command'});syncRoute()}
  function setView(view){const room=K.rooms.find(r=>r.id===view);if(room?.gated){const gate=view==='decision'?decisionGate():executionGate();if(!gate.ok){S.set({view:'blocked',lastError:{code:gate.code,message:gate.message,details:gate.details||{}}});syncRoute();return}}S.set({view,scale:view==='fund-command'?'fund':'deal',lastError:null});syncRoute()}
  function setViewerProjection(v){if(!['associate','partner'].includes(v))return;S.set({viewerProjection:v});}
  function selectSituation(id){S.set({selectedSituationId:id})}
  function selectQuestion(id){S.set({selectedQuestionId:id,drawerObjectId:id,drawerTab:'basis'});syncRoute()}
  function selectArtifact(id){S.set({selectedArtifactId:id,view:'artifacts'});syncRoute()}
  function selectScenario(id){S.set({selectedScenarioId:id})}
  function setWorkstream(id){S.set({selectedWorkstream:id})}
  function openObject(id,tab='basis'){S.set({drawerObjectId:id,drawerTab:tab});syncRoute()}
  function closeDrawer(){S.set({drawerObjectId:null});syncRoute()}
  function setDrawerTab(tab){S.set({drawerTab:tab})}
  function toggleActionRail(){S.set(st=>({actionRailOpen:!st.actionRailOpen}))}
  function toggleNav(){S.set(st=>({navOpen:!st.navOpen}))}
  function toggleInspector(){S.set(st=>({inspectorOpen:!st.inspectorOpen}))}
  function setReducedMotion(v){S.set(st=>({reducedMotion:typeof v==='boolean'?v:!st.reducedMotion}))}
  function clearError(){S.set({lastError:null,error:null})}
  function resetInterface(){const p=projection();S.set({view:'fund-command',scale:'fund',activeEventId:null,activeRun:null,transition:null,transitionIndex:-1,selectedChangeIds:[],selectedCourseId:null,authorityRecord:null,executionPackage:null,executionOutcome:null,settlement:null,selectedGraphVersionId:null,graphVersionDetail:null,drawerObjectId:null,lastError:null,selectedSituationId:p?.fund?.situations?.[0]?.id||null})}

  function getWorkItems(){const p=projection();return p?.deal?.work_items||p?.v16?.work?.items||p?.deal?.question_spine?.flatMap(q=>(q.work_plan||[]).map((w,i)=>({id:w.id||`${q.id}-W${i+1}`,object_id:q.id,question_id:q.id,label:w.label||w.task||`Close ${q.label}`,owner:w.owner||q.owner||'Unassigned',status:w.status||'OPEN',priority:w.priority||q.criticality||'MEDIUM',deadline:w.deadline||'Not set',required_evidence:w.required_evidence||w.evidence||'Not specified',next_action:w.next_action||'Prepare work',authority_boundary:w.authority_boundary||'Professional review'})))||[]}
  async function prepareWork(id){try{const item=getWorkItems().find(x=>x.id===id);const out=await API.adapter().prepareWork(id,{owner:item?.owner,object_id:item?.object_id,actor_id:actor().actor_id});toast(out.message||'Work draft prepared. No external dispatch occurred.','success')}catch(e){toast(e.message,'error')}}

  async function command(q){S.set({commandOpen:true,commandQuery:q,busy:true});try{const out=await API.adapter().search(q||'');S.set({commandResults:out.results||[],busy:false})}catch(e){S.set({commandResults:API.localIndex(projection(),q),busy:false});toast('Backend search unavailable; showing current-projection results.','warning')}}
  function closeCommand(){S.set({commandOpen:false,commandQuery:'',commandResults:[]})}
  function openCommandResult(item){if(!item)return;closeCommand();setView(item.route||item.view||'deal-command');if(item.type&&item.type!=='ROOM')openObject(item.id,'basis')}

  async function refreshSources(){if(!S.get().caseId)return;try{const out=await API.adapter().listSources();S.set({sources:out.sources||projection()?.deal?.source_center?.sources||[]})}catch(_){S.set({sources:projection()?.deal?.source_center?.sources||[]})}}
  async function refreshInbox(){if(!S.get().caseId)return;try{const out=await API.adapter().listInbox();S.set({inbox:Array.isArray(out)?out:(out.items||projection()?.deal?.source_center?.inbox||[])})}catch(_){S.set({inbox:projection()?.deal?.source_center?.inbox||[]})}}
  function setSourceTab(tab){S.set({sourceTab:tab,sourcePage:1})}
  function setSourceSearch(q){S.set({sourceSearch:q,sourcePage:1})}
  function setSourceFilter(name,value){S.set(st=>({sourceFilters:{...st.sourceFilters,[name]:value},sourcePage:1}))}
  function setSourceSort(v){S.set({sourceSort:v,sourcePage:1})}
  function setSourcePage(v){S.set({sourcePage:Math.max(1,Number(v)||1)})}
  function getClaims(){const st=S.get(),filters=st.sourceFilters,q=st.sourceSearch.trim().toLowerCase();let claims=[...(projection()?.deal?.claims||[])];claims=claims.filter(c=>!q||`${c.statement||''} ${c.claim_id||c.id||''} ${c.locator||''} ${c.value??''} ${c.perimeter||''}`.toLowerCase().includes(q));for(const [k,v] of Object.entries(filters)){if(!v)continue;const map={epistemic:'epistemic_class',source:'source_id'};const field=map[k]||k;claims=claims.filter(c=>String(c[field]??'').toLowerCase().includes(String(v).toLowerCase()))}claims.sort((a,b)=>{if(st.sourceSort==='period')return String(a.period||'').localeCompare(String(b.period||''));if(st.sourceSort==='source')return String(a.source_id||'').localeCompare(String(b.source_id||''));if(st.sourceSort==='epistemic')return String(a.epistemic_class||'').localeCompare(String(b.epistemic_class||''));return (b.bears_on?.length||0)-(a.bears_on?.length||0)});return claims}
  async function ingest(form){if(S.get().mobileReadOnly){toast('Source ingestion is available on desktop.','warning');return}S.set({busy:true,operation:'INGEST',ingestError:null});try{const payload={...form,actor_id:actor().actor_id,idempotency_key:uid('INGEST')};if(form.file instanceof File){payload.content_b64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error||new Error('File could not be read'));r.readAsDataURL(form.file)});delete payload.file;}const out=await API.adapter().ingest(payload);const job=out.job||out;S.set(st=>({ingestJobs:[job,...st.ingestJobs.filter(x=>x.job_id!==job.job_id)],activeIngestJobId:job.job_id,busy:false}));pollIngestJob(job.job_id)}catch(e){S.set({busy:false,ingestError:errorShape(e)});toast(`Ingest not started: ${e.message}`,'error')}}
  function pollIngestJob(jobId){clearTimeout(ingestTimer);const tick=async()=>{try{const out=await API.adapter().getJob(jobId),job=out.job||out;S.set(st=>({ingestJobs:st.ingestJobs.map(x=>x.job_id===jobId?job:x),activeIngestJobId:jobId}));if(['COMPLETE','FAILED','ERROR','CANCELLED'].includes(job.status)){if(job.status==='COMPLETE'){await refreshProjection();await refreshSources();await refreshInbox();status(job.admission_status==='PENDING_REVIEW'?'Extraction ready for evidence review':'Ingestion complete')}else{await refreshInbox();toast(job.fix||job.message||'Ingest failed','error')}return}ingestTimer=setTimeout(tick,Math.max(600,job.poll_after_ms||900))}catch(e){toast(`Job status unavailable: ${e.message}`,'error')}};ingestTimer=setTimeout(tick,300)}
  async function openEvidenceReview(jobId){try{S.set({busy:true,operation:'EVIDENCE_REVIEW'});const out=await API.adapter().getEvidenceProposal(jobId);S.set({busy:false,evidenceProposal:out.proposal,evidenceProposalQuestions:out.questions||[],evidenceSemanticPreview:out.semantic_preview||null,sourceTab:'inbox'});status('Review extracted claims and question bindings before admission')}catch(e){S.set({busy:false});toast(`Evidence proposal unavailable: ${e.message}`,'error')}}
  function closeEvidenceReview(){S.set({evidenceProposal:null,evidenceProposalQuestions:[],evidenceSemanticPreview:null})}
  async function admitEvidence(jobId,decision='ADMIT',claims=null){try{S.set({busy:true,operation:'EVIDENCE_ADMISSION'});const payload={decision,actor_id:actor().actor_id,idempotency_key:uid('EVIDENCE')};if(Array.isArray(claims))payload.claims=claims;const out=await API.adapter().admitEvidence(jobId,payload);S.set({busy:false,evidenceProposal:null,evidenceProposalQuestions:[],evidenceSemanticPreview:null});if(decision==='ADMIT')await refreshProjection();await refreshSources();await refreshInbox();toast(out.message||(decision==='ADMIT'?'Reviewed evidence admitted into semantic Current.':'Evidence rejected; Current is unchanged.'),'success')}catch(e){S.set({busy:false});toast(`Evidence decision was not recorded: ${e.message}`,'error')}}
  async function removeSource(id){try{await API.adapter().removeSource(id);await refreshSources();await refreshProjection();toast('Source version retired; history preserved.','success')}catch(e){toast(e.message,'error')}}
  async function saveOpenDeal(payload){try{const out=await API.adapter().openDeal({...payload,actor_id:actor().actor_id,idempotency_key:uid('OPENDEAL')});toast(out.message||'Deal decomposition recorded.','success');await refreshProjection()}catch(e){toast(e.message,'error')}}
  async function saveICRecord(payload){try{const out=await API.adapter().recordIC({...payload,actor_id:actor().actor_id,idempotency_key:uid('IC')});toast(out.message||'IC decision ritual recorded.','success');await refreshProjection()}catch(e){toast(e.message,'error')}}
  async function reviewClaim(id,decision,correction=''){try{const knownAt=now(),note={object_id:id,claim_id:id,kind:'CLAIM_REVIEW',decision,action:decision,correction,text:correction,actor_id:actor().actor_id,timestamp:knownAt,effective_date:knownAt.slice(0,10),known_at:knownAt,idempotency_key:uid('REVIEW')};await API.adapter().addNote(note);const claims=projection()?.deal?.claims||[],c=claims.find(x=>(x.claim_id||x.id)===id);if(c)c.review_status=decision;toast('Review acknowledged by the case store.','success');S.set({renderRevision:S.get().renderRevision+1})}catch(e){toast(`Review not written: ${e.message}`,'error')}}
  async function addNote(id,text){if(!text?.trim())return;try{await API.adapter().addNote({object_id:id,kind:'ANNOTATION',text:text.trim(),actor_id:actor().actor_id,timestamp:now(),idempotency_key:uid('NOTE')});toast('Note acknowledged.','success');await refreshProjection()}catch(e){toast(`Note was not written: ${e.message}`,'error')}}

  function setUnknownTab(tab){S.set({unknownTab:tab,unknownPage:1})}
  function setUnknownSearch(q){S.set({unknownSearch:q,unknownPage:1})}
  function setUnknownSort(v){S.set({unknownSort:v,unknownPage:1})}
  function setUnknownPage(v){S.set({unknownPage:Math.max(1,Number(v)||1)})}
  function setRegistryFilter(kind,q=''){S.set({registryKind:kind||'',registrySearch:q})}
  function copyText(text){navigator.clipboard?.writeText(String(text||''));toast('Copied to clipboard.','success')}
  function deepLink(id){const q=new URLSearchParams(location.hash.replace(/^#/,''));q.set('object',id);copyText(`${location.origin}${location.pathname}${location.search}#${q}`)}
  function exportJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

  function showChangeArrival(){const ev=activeEvent();if(!ev){toast('No pending event is available.','warning');return}S.set({activeEventId:ev.event_id,view:'change-arrival',scale:'deal'});syncRoute()}
  function startReview(){const ev=activeEvent();if(!ev){toast('No pending event is available.','warning');return}S.set({activeEventId:ev.event_id,view:'change-review',selectedChangeIds:[],activeRun:null,transition:null,authorityRecord:null,executionPackage:null,settlement:null,editingTreatment:false,treatmentDraft:ev.proposed_treatment?.statement||ev.proposed_treatment||''});syncRoute()}
  function editTreatment(){S.set({editingTreatment:true})}
  function cancelEdit(){S.set({editingTreatment:false,treatmentDraft:activeEvent()?.proposed_treatment?.statement||activeEvent()?.proposed_treatment||''})}
  function setTreatmentDraft(v){S.set({treatmentDraft:v})}
  async function rejectTreatment(){const ev=activeEvent();if(!ev)return;await addNote(ev.event_id,'Treatment rejected before admission.');S.set({view:'deal-command',activeEventId:null});}
  async function admitTreatment(){
    const ev=activeEvent();if(!ev)return;
    const epoch=++requestEpoch;
    S.set({busy:true,operation:'TRANSITION',lastError:null,view:'change-impact'});
    const payload={treatment_id:ev.treatment_id,treatment_hash:ev.treatment_hash||await API.jsonHash(S.get().treatmentDraft||ev.proposed_treatment),source_version_id:ev.source_version_id,event_id:ev.event_id,actor_id:actor().actor_id,as_of_state_id:S.get().context?.as_of_state_id,as_of_date:S.get().context?.as_of_date,effective_date:ev.effective_date,known_at:now(),timestamp:now(),idempotency_key:`ADMIT-${ev.event_id}-${S.get().sessionId||'SESSION'}`,treatment_text:S.get().treatmentDraft};
    try{
      const out=await API.adapter().admitEvent(ev.event_id,payload);if(epoch!==requestEpoch)return;
      const t=PA.normalizeTransition(out.transition||out),cv=C.safe(C.validateTransition,t);
      if(!cv.ok)throw Object.assign(new Error('Transition failed the frontend contract.'),{code:'INVALID_TRANSITION',details:cv.errors});
      const nextProjection=clone(S.get().projection);
      if(out.candidate_graph&&nextProjection?.deal){
        nextProjection.deal.candidate_graph=clone(out.candidate_graph);
        const versions=[...(nextProjection.deal.graph_versions||[])];
        for(const version of [out.current_graph_version,out.candidate_graph_version])if(version&&!versions.some(x=>x.version_id===version.version_id))versions.push(clone(version));
        nextProjection.deal.graph_versions=versions;
      }
      S.set({busy:false,projection:nextProjection,activeRun:out.run||{run_id:t.run_id,status:'CANDIDATE'},transition:t,transitionIndex:-1,selectedChangeIds:[],context:{...S.get().context,...(out.context||{}),run_id:t.run_id,candidate_state_id:t.candidate_state_id,human_stop_id:t.human_stops?.[0]?.stop_id||null},registry:out.registry||out.registry_events||S.get().registry});
      animateTransition();
    }catch(e){if(epoch!==requestEpoch)return;S.set({busy:false,lastError:errorShape(e)});toast(`Transition rejected: ${e.message}`,'error')}
  }
  function animateTransition(){clearTimeout(transitionTimer);const t=S.get().transition;if(!t)return;let i=0;const n=t.affected_set.length,delay=S.get().reducedMotion?10:Math.max(80,Math.min(420,2200/Math.max(n,1)));S.set({transitionPlaying:true,transitionIndex:-1});const tick=()=>{if(i>=n){S.set({transitionPlaying:false,transitionIndex:Math.max(0,n-1)});status('Candidate consequences ready');return}S.set({transitionIndex:i++});transitionTimer=setTimeout(tick,delay)};tick()}
  function skipTransition(){clearTimeout(transitionTimer);const n=S.get().transition?.affected_set?.length||0;S.set({transitionPlaying:false,transitionIndex:Math.max(0,n-1)})}
  function replayTransition(){animateTransition()}
  function openActionFrontier(){if(!S.get().transition)return;S.set({view:'action-frontier'});syncRoute()}
  function toggleChange(id){S.set(st=>{const x=new Set(st.selectedChangeIds);x.has(id)?x.delete(id):x.add(id);return{selectedChangeIds:[...x]}})}
  function selectAllChanges(){S.set({selectedChangeIds:(S.get().transition?.artifact_change_sets||[]).map(x=>x.artifact_id||x.change_id||x.id)})}
  function decisionGate(){const st=S.get(),t=st.transition,hs=t?.human_stops?.find(x=>x.status==='OPEN')||t?.human_stops?.[0];if(!st.activeRun?.run_id)return{ok:false,code:'RUN_REQUIRED',message:'A valid transition run is required.'};if(!t?.candidate_state_id)return{ok:false,code:'CANDIDATE_REQUIRED',message:'A current Candidate state is required.'};if(!hs)return{ok:false,code:'HUMAN_STOP_REQUIRED',message:'This run does not contain an open Human Stop.'};return{ok:true,human_stop:hs}}
  function executionGate(){const st=S.get();if(!st.authorityRecord)return{ok:false,code:'AUTHORITY_RECORD_REQUIRED',message:'A valid authority record is required.'};if(!st.executionPackage||st.executionPackage.status!=='READY')return{ok:false,code:'EXECUTION_PACKAGE_REQUIRED',message:'A READY immutable execution package is required.'};return{ok:true}}
  async function prepareResponse(){if(!S.get().selectedChangeIds.length){toast('Select at least one change. There is no hidden select-all.','warning');return}try{const out=await API.adapter().prepareRun(S.get().activeRun.run_id,S.get().selectedChangeIds);if(out.run)S.set({activeRun:out.run});const gate=decisionGate();if(gate.ok)setView('decision');else await settleCurrent()}catch(e){toast(e.message,'error')}}
  function selectCourse(id){S.set({selectedCourseId:id})}
  async function attestDecision(){const st=S.get(),gate=decisionGate();if(!gate.ok){setView('decision');return}if(st.mobileReadOnly){toast('Formal attestation is desktop-only.','warning');return}if(!st.selectedCourseId){toast('Select exactly one course of action.','warning');return}const required=gate.human_stop.required_authority_level||'DEAL_PARTNER';if(!hasAuthority(required)){S.set({view:'blocked',lastError:{code:'INSUFFICIENT_AUTHORITY',message:`${required} is required; viewer projection does not grant authority.`}});return}try{S.set({busy:true,operation:'ATTEST'});const out=await API.adapter().attest(st.activeRun.run_id,{run_id:st.activeRun.run_id,candidate_state_id:st.transition.candidate_state_id,human_stop_id:gate.human_stop.stop_id,course_id:st.selectedCourseId,actor_id:actor().actor_id,actor_role:actor().role,artifact_hash:st.transition.replay_hash,idempotency_key:`AUTH-${st.activeRun.run_id}-${st.selectedCourseId}`});const ar=out.authority_record;C.validateAuthorityRecord(ar);S.set({busy:false,authorityRecord:ar,executionPackage:out.execution_package||null,registry:out.registry||st.registry});if(ar.effect_type==='DEFER'||!out.execution_package){await settleCurrent({deferred:true});return}setView('execution')}catch(e){S.set({busy:false});toast(`Attestation rejected: ${e.message}`,'error')}}
  async function sendExecution(simulateFailure=false){const gate=executionGate();if(!gate.ok){setView('execution');return}try{S.set({busy:true,operation:'DELIVERY',executionPackage:{...S.get().executionPackage,status:'SENDING'}});const out=await API.adapter().sendPackage(S.get().executionPackage.execution_package_id,simulateFailure);const pkg=out.execution_package||out;S.set({busy:false,executionPackage:pkg,executionOutcome:out,registry:out.registry||S.get().registry});if(['ACCEPTED','DELIVERED'].includes(pkg.status))toast('Server acknowledged the simulated package. No external system was contacted.','success');else toast(`Package state: ${pkg.status}`,'warning')}catch(e){S.set(st=>({busy:false,executionPackage:{...st.executionPackage,status:'FAILED'}}));toast(`Not sent: ${e.message}`,'error')}}
  async function settleCurrent(extra={}){const st=S.get();if(!st.selectedChangeIds.length){toast('Settlement requires explicit selected changes.','warning');return}try{S.set({busy:true,operation:'SETTLEMENT'});const out=await API.adapter().settle(st.activeRun.run_id,{run_id:st.activeRun.run_id,candidate_state_id:st.transition.candidate_state_id,prior_state_id:st.transition.prior_state_id,as_of_state_id:st.context.as_of_state_id,as_of_date:st.context.as_of_date,effective_date:new Date().toISOString().slice(0,10),selected_change_ids:st.selectedChangeIds,human_stop_ids:(st.transition.human_stops||[]).map(x=>x.stop_id),authority_record_ids:st.authorityRecord?[st.authorityRecord.authority_record_id]:[],execution_package_ids:st.executionPackage?[st.executionPackage.execution_package_id]:[],actor_id:actor().actor_id,allow_partial_settlement:true,idempotency_key:`SETTLE-${st.activeRun.run_id}-${[...st.selectedChangeIds].sort().join('-')}`,...extra});const nextProjection=out.projection?.projection||out.projection||st.projection;S.set({busy:false,settlement:out,registry:out.registry||st.registry,context:out.context||st.context,projection:nextProjection,view:'settled'});status('Canonical Current state returned by the server');syncRoute()}catch(e){S.set({busy:false,lastError:errorShape(e)});toast(`Settlement rejected: ${e.message}`,'error')}}
  async function openReplay(id){S.set({selectedReplayId:id,view:'replay'});syncRoute();try{const out=await API.adapter().replay(id);if(out.as_of_date)await refreshProjection({asOfDate:out.as_of_date,preserveView:true});S.set({replayResponse:out,selectedReplayId:out.event?.event_id||id,selectedAsOfDate:out.as_of_date||S.get().selectedAsOfDate,view:'replay'});syncRoute()}catch(e){toast(`Replay unavailable: ${e.message}`,'error')}}
  async function openGraphVersion(id){if(!id)return;S.set({busy:true,operation:'GRAPH_VERSION'});try{const out=await API.adapter().getGraphVersion(id);S.set({busy:false,selectedGraphVersionId:id,graphVersionDetail:out,view:'replay'});syncRoute()}catch(e){S.set({busy:false});toast(`Graph version unavailable: ${e.message}`,'error')}}
  async function newDemoSession(){try{const out=await API.adapter().newSession(S.get().caseId,'partner');sessionStorage.setItem('panta-v20-session',out.session_id);S.set({sessionId:out.session_id,registry:[]});location.search=`?mode=${modeQuery()}&case=${encodeURIComponent(S.get().caseId)}&session=${encodeURIComponent(out.session_id)}`}catch(e){toast(e.message,'error')}}

  window.PantaActions={boot,applyProjection,refreshProjection,setAsOfDate,setAsOfState,refreshSources,refreshInbox,openCase,setView,setViewerProjection,selectSituation,selectQuestion,selectArtifact,selectScenario,setWorkstream,openObject,closeDrawer,setDrawerTab,toggleActionRail,toggleNav,toggleInspector,setReducedMotion,clearError,resetInterface,getWorkItems,prepareWork,command,closeCommand,openCommandResult,activeEvent,setSourceTab,setSourceSearch,setSourceFilter,setSourceSort,setSourcePage,getClaims,ingest,pollIngestJob,openEvidenceReview,closeEvidenceReview,admitEvidence,removeSource,saveOpenDeal,saveICRecord,reviewClaim,addNote,setUnknownTab,setUnknownSearch,setUnknownSort,setUnknownPage,setRegistryFilter,copyText,deepLink,exportJSON,startReview,editTreatment,cancelEdit,setTreatmentDraft,rejectTreatment,admitTreatment,replayTransition,skipTransition,openActionFrontier,toggleChange,selectAllChanges,decisionGate,executionGate,prepareResponse,selectCourse,attestDecision,sendExecution,settleCurrent,openReplay,openGraphVersion,newDemoSession,showToast:toast,showChangeArrival,hasAuthority,authorityLevel};
})();
