#!/usr/bin/env python3
"""
bind_questions_e3.py — bind E3 claims to the 20 Keystone diligence questions.

Uses two rule layers (no LLM):
  R1  metric → question IDs   (primary, deterministic)
  R2  keyword scan of statement text → question IDs (secondary)

Outputs:
  bindings.json        — claim_id → [question_ids], confidence
  question_summary.txt — per-question claim count + samples
  binding_report.txt   — coverage / recall / unbound stats

Usage:
  python3 tools/bind_questions_e3.py --e3 pipeline_out/e3/K-IC/e3_claims.json \\
      --out pipeline_out/e3/K-IC/bindings/
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# ── 20 Keystone diligence questions ──────────────────────────────────────────
QUESTIONS: dict[str, str] = {
    "Q-01": "Which billing accounts share parent-company relationships?",
    "Q-02": "What percentage of revenue is generated by the largest parent customer across all billing accounts?",
    "Q-03": "Which customer agreements have minimum-volume commitments, and which can be reduced or terminated on short notice?",
    "Q-04": "How much revenue is scheduled/programmatic versus repeat-project versus new/discrete project work?",
    "Q-05": "Which top customers have non-standard pricing, margin or service-level terms?",
    "Q-06": "Which EBITDA adjustments are implemented, supportable and non-recurring?",
    "Q-07": "What is the support for the pricing and utilization initiative add-back?",
    "Q-08": "What is the correct normalized working-capital target?",
    "Q-09": "What portion of unbilled WIP is aged, disputed or missing customer approval?",
    "Q-10": "Which liabilities are debt-like and which are ordinary working-capital items?",
    "Q-11": "Which time-entry, billing, ERP and customer-master systems are still active?",
    "Q-12": "What failed or was delayed in prior integrations and systems migrations?",
    "Q-13": "Who owns the post-close integration program and what is the required cash budget?",
    "Q-14": "How are utilization, rework and project profitability defined across branches?",
    "Q-15": "Which contracts require change-of-control notice or consent?",
    "Q-16": "What is the treatment of the founder-related headquarters lease?",
    "Q-17": "What EBITDA basis will lenders use for covenant calculations?",
    "Q-18": "What are the proposed limits on add-backs, cash netting, acquisition capacity and minimum liquidity?",
    "Q-19": "Which executives and branch leaders require retention arrangements?",
    "Q-20": "What board approvals should be required before acquisitions or major systems cutovers?",
}

# Vault question IDs → list of question IDs (for cross-reference reporting)
VAULT_TO_Q: dict[str, list[str]] = {
    "kq-01-parent-concentration":  ["Q-01", "Q-02"],
    "kq-02-revenue-durability":    ["Q-04", "Q-05"],
    "kq-03-contract-protections":  ["Q-03"],
    "kq-04-ebitda-adjustments":    ["Q-06", "Q-07"],
    "kq-05-working-capital":       ["Q-08"],
    "kq-06-wip-quality":           ["Q-09"],
    "kq-07-debt-classification":   ["Q-10"],
    "kq-08-integration-systems":   ["Q-11", "Q-14"],
    "kq-09-integration-history":   ["Q-12", "Q-13"],
    "kq-10-covenant-definition":   ["Q-17", "Q-18"],
    "kq-11-change-of-control":     ["Q-15", "Q-16"],
    "kq-12-governance":            ["Q-19", "Q-20"],
}

# ── R1: metric → question IDs ─────────────────────────────────────────────────
METRIC_TO_Q: dict[str, list[str]] = {
    # Concentration / revenue
    "Customer Concentration":      ["Q-01", "Q-02"],
    "Active Billing Accounts":     ["Q-01"],
    "Customer Count":              ["Q-01"],
    "Customer Retention":          ["Q-02"],
    "Revenue":                     ["Q-04"],
    "Revenue Growth":              ["Q-04"],
    "Recurring Revenue":           ["Q-04"],
    "Revenue Quality":             ["Q-04"],
    "Gross Profit":                ["Q-04", "Q-06"],
    "Gross Margin":                ["Q-06"],
    # Contract terms
    "Customer Contract Terms":     ["Q-03", "Q-05"],
    "Contract Terms":              ["Q-03", "Q-05"],
    # EBITDA / adjustments
    "EBITDA":                      ["Q-06"],
    "EBITDA Adjustment":           ["Q-06"],
    "EBITDA Add-back":             ["Q-06", "Q-07"],
    "EBITDA Margin":               ["Q-06"],
    "Adjustment Supportability":   ["Q-06"],
    "Earnings Quality Risk":       ["Q-06"],
    "Net Income":                  ["Q-06"],
    # Working capital
    "Working Capital":             ["Q-08"],
    "Net Working Capital":         ["Q-08"],
    "Net Working Capital Target":  ["Q-08"],
    "Net Working Capital Adjustment": ["Q-08"],
    "DSO":                         ["Q-08"],
    "DPO":                         ["Q-08"],
    "Operating Cash Flow":         ["Q-08"],
    # WIP
    "Revenue Quality":             ["Q-09"],
    # Debt / structure
    "Gross Debt":                  ["Q-10"],
    "Net Debt":                    ["Q-10"],
    "First-Lien Debt":             ["Q-10"],
    "Seller Rollover":             ["Q-10"],
    "Sponsor Equity":              ["Q-10"],
    "Leverage":                    ["Q-10"],
    "Equity Value":                ["Q-10"],
    "Gross Profit":                ["Q-10"],
    # Integration / systems
    "Systems Integration Risk":    ["Q-11", "Q-12"],
    "Integration Risk":            ["Q-11", "Q-12"],
    "Headcount":                   ["Q-13", "Q-19"],
    "Acquisition Count":           ["Q-12", "Q-13"],
    # Operational KPIs
    "Capex":                       ["Q-14"],
    # Debt structure / covenant
    "Covenant Threshold":          ["Q-17", "Q-18"],
    "Covenant EBITDA":             ["Q-17"],
    "Revolver Capacity":           ["Q-18"],
    "DDTL Availability":           ["Q-18"],
    # Returns / enterprise value (bear on EBITDA basis)
    "Enterprise Value":            ["Q-06"],
    "Entry Multiple":              ["Q-06"],
    "Exit Multiple":               ["Q-06"],
    "Exit EV":                     ["Q-06"],
    "Exit Horizon":                ["Q-06"],
    "MOIC":                        ["Q-06"],
    "IRR":                         ["Q-06"],
    # IC
    "IC Conditions":               ["Q-17", "Q-18"],
    "IC Vote":                     ["Q-17"],
    # Debt service / covenant
    "Interest Coverage":           ["Q-17"],
    # Governance / retention
    "Key Person Risk":             ["Q-19"],
    "Team Tenure":                 ["Q-19"],
}

# ── R2: keyword patterns → question IDs ──────────────────────────────────────
KEYWORD_TO_Q: list[tuple[re.Pattern, list[str]]] = [
    # Concentration / revenue
    (re.compile(r"parent.{0,20}(customer|account|concentration)", re.I), ["Q-01", "Q-02"]),
    (re.compile(r"billing account", re.I), ["Q-01"]),
    (re.compile(r"concentration.{0,30}(revenue|account|customer)", re.I), ["Q-01", "Q-02"]),
    (re.compile(r"riverton|apex.{0,10}manufactur|cityworks|clinica|harbor.{0,10}util|medcore|metro.{0,10}util|precision.{0,10}compon|state.{0,10}infra", re.I), ["Q-01"]),
    (re.compile(r"minimum.{0,20}(volume|commit)", re.I), ["Q-03"]),
    (re.compile(r"terminat.{0,20}(notice|right|short)", re.I), ["Q-03"]),
    (re.compile(r"scheduled.{0,30}(revenue|work|project)", re.I), ["Q-04"]),
    (re.compile(r"programmat.{0,20}(revenue|work)", re.I), ["Q-04"]),
    (re.compile(r"repeat.{0,20}project", re.I), ["Q-04"]),
    (re.compile(r"non-standard.{0,20}(pricing|margin|sla|service.level)", re.I), ["Q-05"]),
    # EBITDA
    (re.compile(r"(add.back|addback).{0,30}(pricing|utilization|initiative)", re.I), ["Q-07"]),
    (re.compile(r"pricing.{0,30}utilization.{0,30}(add.back|initiative)", re.I), ["Q-07"]),
    (re.compile(r"non.recurring.{0,20}adjust", re.I), ["Q-06"]),
    # WIP
    (re.compile(r"(unbilled|wip).{0,30}(aged|aging|disputed|dispute|approv)", re.I), ["Q-09"]),
    (re.compile(r"work.in.progress.{0,30}(aged|aging|disputed)", re.I), ["Q-09"]),
    # Debt like
    (re.compile(r"debt.like", re.I), ["Q-10"]),
    (re.compile(r"deferred.tax", re.I), ["Q-10"]),
    (re.compile(r"headquarter.{0,20}lease", re.I), ["Q-16"]),
    (re.compile(r"founder.{0,20}lease", re.I), ["Q-16"]),
    # Systems / integration
    (re.compile(r"(time.entry|erp|customer.master|billing.system)", re.I), ["Q-11"]),
    (re.compile(r"(cutover|migration|integration).{0,30}(fail|delay|histor)", re.I), ["Q-12"]),
    (re.compile(r"integration.{0,20}(program|budget|cash|own)", re.I), ["Q-13"]),
    (re.compile(r"(utilization|rework|project.profitability).{0,30}(defin|measur)", re.I), ["Q-14"]),
    # Change of control
    (re.compile(r"change.of.control", re.I), ["Q-15"]),
    (re.compile(r"(consent|notice).{0,30}(contract|customer|agreement)", re.I), ["Q-15"]),
    # Covenant
    (re.compile(r"covenant.{0,20}(ebitda|basis|defin)", re.I), ["Q-17"]),
    (re.compile(r"lender.{0,30}(covenant|ebitda)", re.I), ["Q-17"]),
    (re.compile(r"(add.back|acquisition.capacity|minimum.liquidity|cash.netting).{0,30}limit", re.I), ["Q-18"]),
    # Retention / governance
    (re.compile(r"retention.{0,20}(execut|branch|leader|arrang)", re.I), ["Q-19"]),
    (re.compile(r"(execut|branch.leader).{0,20}retent", re.I), ["Q-19"]),
    (re.compile(r"board.{0,20}approv.{0,30}(acquis|system|cutover)", re.I), ["Q-20"]),
    (re.compile(r"governance.{0,20}(acquis|cutover|major)", re.I), ["Q-20"]),
]


def bind_claim(claim: dict, compiler_meta: dict) -> list[str]:
    """Return sorted list of question IDs this claim bears on."""
    bound: set[str] = set()
    metric = compiler_meta.get("metric", "")
    stmt = claim.get("statement", "")

    # R1: metric lookup
    if metric in METRIC_TO_Q:
        bound.update(METRIC_TO_Q[metric])

    # R2: keyword scan
    text = stmt
    for pat, qids in KEYWORD_TO_Q:
        if pat.search(text):
            bound.update(qids)

    return sorted(bound)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--e3", required=True, help="e3_claims.json path")
    ap.add_argument("--out", required=True, help="output directory")
    args = ap.parse_args()

    e3_path = Path(args.e3)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(e3_path) as f:
        e3 = json.load(f)

    claims = e3["claims"]
    compiler_fields = {
        cf["claim_id"]: cf
        for cf in e3.get("extraction_metadata", {}).get("compiler_fields_per_claim", [])
    }

    # Build bindings
    bindings: list[dict] = []
    q_to_claims: dict[str, list[str]] = {q: [] for q in QUESTIONS}
    unbound: list[str] = []

    for c in claims:
        cid = c["claim_id"]
        meta = compiler_fields.get(cid, {})
        qids = bind_claim(c, meta)
        bindings.append({
            "claim_id": cid,
            "statement": c["statement"],
            "metric": meta.get("metric", ""),
            "source_id": c["source_id"],
            "question_ids": qids,
            "rule": "R1+R2" if qids else "none",
        })
        if qids:
            for qid in qids:
                q_to_claims[qid].append(cid)
        else:
            unbound.append(cid)

    # ── Stats ─────────────────────────────────────────────────────────────────
    total = len(claims)
    bound_count = total - len(unbound)
    covered_qs = [q for q in QUESTIONS if q_to_claims[q]]
    uncovered_qs = [q for q in QUESTIONS if not q_to_claims[q]]
    coverage = len(covered_qs) / len(QUESTIONS)

    # Write bindings JSON
    out = {
        "manifest_id": e3.get("manifest_id"),
        "deal": e3.get("deal"),
        "total_claims": total,
        "bound_claims": bound_count,
        "unbound_claims": len(unbound),
        "questions_covered": len(covered_qs),
        "questions_total": len(QUESTIONS),
        "coverage_recall": round(coverage, 3),
        "bindings": bindings,
        "q_coverage": {q: len(q_to_claims[q]) for q in QUESTIONS},
    }
    (out_dir / "bindings.json").write_text(json.dumps(out, indent=2))

    # Write human-readable report
    lines = [
        "E3 Question Binding Report",
        "=" * 50,
        f"  Manifest    : {e3.get('manifest_id')}",
        f"  Deal        : {e3.get('deal')}",
        f"  Total claims: {total}",
        f"  Bound claims: {bound_count} ({100*bound_count/total:.1f}%)",
        f"  Unbound     : {len(unbound)} ({100*len(unbound)/total:.1f}%)",
        f"  Questions covered: {len(covered_qs)} / {len(QUESTIONS)}",
        f"  Coverage recall : {coverage:.1%}",
        "",
        "Per-question claim counts:",
    ]
    for qid, qtxt in QUESTIONS.items():
        count = len(q_to_claims[qid])
        flag = "" if count > 0 else "  ← ZERO COVERAGE"
        lines.append(f"  {qid}: {count:3d}  {qtxt[:65]}{flag}")

    lines += ["", "Uncovered questions:"]
    if uncovered_qs:
        for qid in uncovered_qs:
            lines.append(f"  {qid}: {QUESTIONS[qid]}")
    else:
        lines.append("  None — full coverage.")

    lines += ["", "Metrics with no question mapping (top unbound):"]
    unbound_metrics: dict[str, int] = {}
    for b in bindings:
        if not b["question_ids"]:
            m = b["metric"] or "(no metric)"
            unbound_metrics[m] = unbound_metrics.get(m, 0) + 1
    for m, cnt in sorted(unbound_metrics.items(), key=lambda x: -x[1])[:15]:
        lines.append(f"  {cnt:3d}  {m}")

    report_text = "\n".join(lines)
    (out_dir / "binding_report.txt").write_text(report_text)
    print(report_text)


if __name__ == "__main__":
    main()
