#!/usr/bin/env python3
"""G1: a formula may not call itself ARITHMETIC unless it can actually execute.

PAN-121 (tools/formula_contract.py) measured the gap and reported it. These
tests pin the enforcing half: the contract is imposed when the mapping is
produced, so an artifact stops promising a computation the evaluator declines
to perform.

The runtime was never the weak point -- model_evaluator already turns every
violation into a declared limit. What was wrong is that the mapping SAID
ARITHMETIC for 10 of the 12 formulas on the real K-PRE bundle.
"""
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.formula_contract import (  # noqa: E402
    UNEXECUTABLE_TYPE, contract_violations, enforce_contract,
)
from tools.model_evaluator import EXECUTABLE_TYPES, evaluate_mapping  # noqa: E402

K_PRE = ROOT / "pipeline_out" / "e3" / "K-PRE" / "adapter_alpha" / "execution_mapping.json"


def _mapping(**formula) -> dict:
    base = {
        "formula_id": "F-T", "output_id": "MN-OUT", "evaluation_type": "ARITHMETIC",
        "expression_or_function_ref": "a + b",
        "variable_binding": {"a": "MN-A", "b": "MN-B"},
    }
    base.update(formula)
    return {
        "model_nodes": [
            {"model_node_id": "MN-A", "computational_form": "DIRECT_INPUT", "initial_value": 2.0},
            {"model_node_id": "MN-B", "computational_form": "DIRECT_INPUT", "initial_value": 3.0},
            {"model_node_id": "MN-OUT"},
        ],
        "formulas": [base],
    }


class ContractEnforcementTests(unittest.TestCase):
    def test_a_satisfiable_formula_is_left_alone_and_computes(self) -> None:
        """The guard: enforcement must not disturb a formula that is fine."""
        m = _mapping()
        self.assertEqual(enforce_contract(m), [])
        self.assertEqual(m["formulas"][0]["evaluation_type"], "ARITHMETIC")
        self.assertEqual(evaluate_mapping(m)["values"]["MN-OUT"], 5.0)

    def test_unbound_name_is_rejected(self) -> None:
        """G1's 'done when': a mapping with unbound names does not pass."""
        m = _mapping(expression_or_function_ref="a + b + firm_ebitda")
        self.assertTrue(contract_violations(m), "unbound operand must be reported")
        self.assertIn("firm_ebitda", contract_violations(m)[0])

    def test_binding_to_a_workbook_cell_is_not_a_model_node(self) -> None:
        """'Inputs!B23' looks bound and is not -- the failure PAN-121 documented."""
        m = _mapping(variable_binding={"a": "MN-A", "b": "Inputs!B23"})
        self.assertTrue(contract_violations(m))

    def test_a_failing_formula_is_downgraded_not_deleted(self) -> None:
        """It stays as the description of intent, minus the false claim."""
        m = _mapping(expression_or_function_ref="a + b + firm_ebitda")
        downgraded = enforce_contract(m)
        self.assertEqual(len(downgraded), 1)
        f = m["formulas"][0]
        self.assertEqual(f["evaluation_type"], UNEXECUTABLE_TYPE)
        self.assertTrue(f["coverage_limit"], "the reason must travel with it")
        self.assertEqual(f["expression_or_function_ref"], "a + b + firm_ebitda")

    def test_downgrade_makes_the_evaluator_declare_a_limit(self) -> None:
        """Why no evaluator change is needed: EXECUTABLE_TYPES is {ARITHMETIC}."""
        self.assertNotIn(UNEXECUTABLE_TYPE, EXECUTABLE_TYPES)
        m = _mapping(expression_or_function_ref="a + b + firm_ebitda")
        enforce_contract(m)
        limits = evaluate_mapping(m)["declared_limits"]
        self.assertTrue(any(l.get("formula_id") == "F-T" for l in limits))
        self.assertNotIn("MN-OUT", evaluate_mapping(m)["values"])


class RealBundleTests(unittest.TestCase):
    """The measurement the ticket is built on, kept honest against drift."""

    @unittest.skipUnless(K_PRE.exists(), "K-PRE bundle not present")
    def test_the_real_mapping_overstates_what_it_can_execute(self) -> None:
        m = json.loads(K_PRE.read_text(encoding="utf-8"))
        arithmetic = [f for f in m["formulas"] if f.get("evaluation_type") == "ARITHMETIC"]
        downgraded = enforce_contract(m)
        self.assertGreater(
            len(downgraded), len(arithmetic) // 2,
            "most ARITHMETIC formulas on this bundle cannot satisfy the contract; "
            "if this now fails the mapping was regenerated by a real compiler",
        )
        # and every survivor genuinely executes
        for f in m["formulas"]:
            if f.get("evaluation_type") == "ARITHMETIC":
                self.assertEqual(contract_violations({**m, "formulas": [f]}), [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
